// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// ภาษาไทย — โครงสร้างและคำแปลส่วนติดต่อผู้ใช้
extension Strings {
    static let th = Strings(
        statusIdleTooltip: "Vorssaint: สลีปตามปกติ",
        statusActiveUntil: "Vorssaint: ตื่นอยู่จนถึง",
        statusActiveIndefinite: "Vorssaint: ตื่นอยู่ตลอดเวลา",
        menuEnableAwake: "เปิดการคงสถานะตื่น",
        menuDisableAwake: "ปิดการคงสถานะตื่น",
        menuActivateFor: "เปิดใช้งานเป็นเวลา…",
        menuSettings: "การตั้งค่า…",
        menuAbout: "เกี่ยวกับ Vorssaint",
        menuQuit: "ออกจาก Vorssaint",
        menuHide: "ซ่อน Vorssaint",
        menuHideOthers: "ซ่อนอื่นๆ",
        menuShowAll: "แสดงทั้งหมด",
        menuEdit: "แก้ไข",
        menuUndo: "เลิกทำ",
        menuRedo: "ทำซ้ำ",
        actionClear: "ล้าง",
        actionRemove: "เอาออก",
        actionBack: "ย้อนกลับ",
        actionSearch: "ค้นหา",
        actionMute: "ปิดเสียง",
        actionUnmute: "เปิดเสียง",
        actionPlay: "เล่น",
        actionPause: "หยุดชั่วคราว",
        menuCut: "ตัด",
        menuCopy: "คัดลอก",
        menuPaste: "วาง",
        menuSelectAll: "เลือกทั้งหมด",
        menuWindow: "หน้าต่าง",
        menuMinimize: "ย่อ",
        menuZoom: "ซูม",
        menuClose: "ปิด",
        minutes15: "15 นาที",
        minutes30: "30 นาที",
        hour1: "1 ชั่วโมง",
        hours2: "2 ชั่วโมง",
        hours4: "4 ชั่วโมง",
        hours8: "8 ชั่วโมง",
        indefinitely: "ไม่จำกัดเวลา",
        indefinite: "ไม่มีกำหนด",
        panelSettings: "การตั้งค่า",
        panelQuit: "ล้มเลิก",
        panelHotkeyHint: "สลับทางลัด",
        keepAwakeTitle: "คงสถานะตื่น",
        keepAwakeEndsIn: "สิ้นสุดใน",
        keepAwakeUntilDisabled: "ใช้งานอยู่จนกว่าคุณจะปิด",
        keepAwakeNormalRules: "Mac ปฏิบัติตามกฎพลังงานปกติ",
        keepAwakeUntilLabel: "จนกระทั่ง",
        keepAwakeUntilStart: "เริ่ม",
        keepAwakeOptions: "ตัวเลือก",
        keepAwakeMouseJiggle: "เลื่อนตัวชี้เล็กน้อย",
        keepAwakeMouseJiggleCaption: "ในระหว่างเซสชัน ให้เลื่อนตัวชี้เล็กน้อยตามช่วงเวลาที่เลือก",
        keepAwakeMouseJiggleInterval: "ช่วงเวลา",
        keepAwakeActiveIconLabel: "ไอคอนที่ใช้งานอยู่",
        keepAwakeActiveIconVorssaint: "วอร์สเซนต์",
        keepAwakeActiveIconCoffee: "กาแฟ",
        keepAwakeActiveIconEye: "ดวงตา",
        keepAwakeActiveIconMoon: "ดวงจันทร์",
        keepAwakeActiveIconLight: "หลอดไฟ",
        keepAwakeIconTintLabel: "สีไอคอนที่ใช้งานอยู่",
        keepAwakeIconTintOrange: "ส้ม",
        keepAwakeIconTintGreen: "สีเขียว",
        keepAwakeIconTintBlue: "สีฟ้า",
        keepAwakeIconTintPurple: "สีม่วง",
        keepAwakeIconTintPink: "สีชมพู",
        keepAwakeIconTintNone: "ไม่มีสี",
        durationLabel: "ระยะเวลา",
        clamshellTitle: "ดำเนินการต่อโดยปิดฝา",
        clamshellOnCaption: "การนอนหลับปิดการใช้งานอย่างสมบูรณ์ คำนึงถึงพลัง",
        clamshellNeedsSession: "ใช้ทุกครั้งที่มีการใช้งาน \"Keep wake\"",
        clamshellReady: "พร้อม. สลับโดยไม่ต้องใช้รหัสผ่าน",
        clamshellNeedsPassword: "จะถามรหัสผ่านผู้ดูแลระบบหนึ่งครั้ง",
        systemSection: "ระบบ",
        temperatures: "อุณหภูมิ",
        cpuLabel: "ซีพียู",
        gpuLabel: "จีพียู",
        batteryLabel: "แบตเตอรี่",
        usageSection: "การใช้ฮาร์ดแวร์",
        memorySection: "หน่วยความจำ",
        memoryPressure: "ความดัน",
        memorySwapUsed: "แลกใช้แล้ว",
        memoryCompressed: "บีบอัด",
        memoryCachedFiles: "ไฟล์แคช",
        pressureNormal: "ปกติ",
        pressureWarning: "คำเตือน",
        pressureCritical: "วิกฤต",
        monitorUnavailable: "เซ็นเซอร์ไม่พร้อมใช้งานบน Mac เครื่องนี้",
        energyAppsTitle: "แอปที่ใช้พลังงานจำนวนมาก",
        energyAppsIdle: "ไม่มีการใช้พลังงานอย่างมีนัยสำคัญ",
        notifySessionEndedTitle: "เซสชันสิ้นสุดแล้ว",
        notifySessionEndedBody: "หมดเวลาแล้ว Mac จะเข้าสู่โหมดสลีปตามปกติอีกครั้ง",
        notifyBatteryTitle: "Vorssaint ปิดการใช้งาน",
        notifyBatteryBody: "แบตเตอรี่เหลือน้อย การนอนหลับปกติได้รับการฟื้นฟูเพื่อปกป้องประจุ",
        adminPromptClamshellOn: "Vorssaint ต้องการรหัสผ่านของคุณเพื่อให้ Mac ทำงานโดยปิดฝาไว้",
        adminPromptClamshellOff: "Vorssaint ต้องการรหัสผ่านของคุณเพื่อคืนค่าการนอนหลับปกติของ Mac",
        adminPromptRecover: "Vorssaint ออกในขณะที่ปิดโหมดสลีปของ Mac ป้อนรหัสผ่านเพื่อคืนค่าการนอนหลับปกติ",
        adminPromptUpdate: "Vorssaint ต้องการรหัสผ่านของคุณเพื่อติดตั้งการอัปเดต",
        adminPromptSudoersInstall: "Vorssaint จะสร้างกฎแบบจำกัด (pmset ปิดใช้งานโหมดสลีปเท่านั้น) เพื่อสลับโหมดปิดโดยไม่ต้องถามรหัสผ่าน นี่เป็นครั้งเดียวที่จำเป็นต้องใช้รหัสผ่าน",
        adminPromptSudoersRemove: "Vorssaint จะลบกฎฝาปิดแบบไม่ต้องใส่รหัสผ่าน",
        settingsTitle: "การตั้งค่า Vorssaint",
        tabGeneral: "ทั่วไป",
        tabEnergy: "พลังงาน",
        tabMouse: "เมาส์และแทร็กแพด",
        tabSwitcher: "ตัวสลับ",
        tabAdvanced: "ขั้นสูง",
        tabAbout: "เกี่ยวกับ",
        tabReleaseNotes: "มีอะไรใหม่",
        releaseNotesOnUpdateToggle: "แสดงว่ามีอะไรใหม่หลังจากอัปเดต",
        minimalWindowPreviews: "การแสดงตัวอย่างน้อยที่สุด",
        minimalWindowPreviewsCaption: "ซ่อนชื่อเรื่อง ปุ่ม และรายละเอียดการตกแต่งในตัวอย่าง Dock และตัวสลับ การเลือกจะยังคงมองเห็นได้",
        previewSizeLabel: "ขนาดตัวอย่าง",
        previewSizeNormal: "ปกติ",
        previewSizeLarge: "ใหญ่",
        previewSizeXLarge: "ใหญ่พิเศษ",
        settingsGroupFeatures: "คุณสมบัติ",
        advancedResetSection: "สิทธิ์",
        advancedResetDescription: "ลบทุกสิทธิ์ที่คุณให้ Vorssaint (การเข้าถึง การบันทึกหน้าจอ การเข้าถึงดิสก์แบบเต็ม และอื่นๆ) รายการเข้าสู่ระบบ และกฎฝาปิด มีประโยชน์ในการเริ่มต้นใหม่หรือก่อนที่จะถอนการติดตั้ง แอปยังคงติดตั้งอยู่",
        advancedClearButton: "ล้างสิทธิ์ทั้งหมด",
        advancedCleared: "ล้างสิทธิ์แล้ว",
        advancedClearFailed: "สิทธิ์บางอย่างหรือกฎฝาปิดไม่สามารถลบออกได้ ลองอีกครั้งและอนุญาตการร้องขอรหัสผ่านหากปรากฏขึ้น",
        advancedClearConfirmTitle: "ล้างสิทธิ์ทั้งหมดใช่ไหม",
        advancedClearConfirmBody: "คุณลักษณะที่ต้องได้รับสิทธิ์จะหยุดทำงานจนกว่าคุณจะให้สิทธิ์อีกครั้ง การตั้งค่าของคุณจะถูกเก็บไว้",
        advancedUninstallSection: "ถอนการติดตั้ง",
        advancedUninstallDescription: "ทำทุกอย่างที่กล่าวมา จากนั้นลบการตั้งค่าออก และย้าย Vorssaint ไปที่ถังขยะ โดยไม่ทิ้งสิ่งใดไว้ข้างหลัง แอปจะหยุดทำงานเมื่อเสร็จสิ้น คุณสามารถติดตั้งใหม่ได้ตลอดเวลา",
        advancedUninstallButton: "ถอนการติดตั้ง Vorssaint อย่างสมบูรณ์",
        advancedUninstallConfirmTitle: "ถอนการติดตั้ง Vorssaint?",
        advancedUninstallConfirmBody: "Vorssaint จะล้างสิทธิ์ ลบการตั้งค่า และย้ายไปที่ถังขยะ จากนั้นออก การดำเนินการนี้ไม่สามารถยกเลิกได้จากแอป แต่จะยังคงอยู่ในถังขยะจนกว่าคุณจะล้างข้อมูล",
        advancedUninstallFailedTitle: "การถอนการติดตั้งหยุดแล้ว",
        advancedUninstallFailedBody: "Vorssaint ไม่สามารถคืนการตั้งค่าระบบที่เปลี่ยนแปลงไป เช่น สลีป ความเร็วพัดลม หรือการเร่งความเร็วเมาส์ ไม่มีอะไรถูกลบออก ลองอีกครั้งและอนุญาตการร้องขอรหัสผ่านหากปรากฏขึ้น",
        launchAtLogin: "เปิดตัวเมื่อเข้าสู่ระบบ",
        languageLabel: "ภาษา",
        menuBarSection: "แถบเมนู",
        showCountdown: "แสดงเวลาที่เหลืออยู่ถัดจากไอคอน",
        globalHotkeySection: "ทางลัดระดับโลก",
        hotkeyToggle: "เปิดใช้งานทางลัดสำหรับ \"Keep wake\"",
        hotkeyCaption: "ใช้งานได้กับทุกแอป ไม่มีสิทธิ์พิเศษ",
        sessionSection: "การประชุม",
        defaultDurationLabel: "ระยะเวลาเริ่มต้น",
        keepAwakeAutoStart: "จงตื่นตัวเมื่อ Vorssaint เปิดขึ้น",
        keepAwakeAutoStartCaption: "เริ่มเซสชันด้วยระยะเวลาเริ่มต้น",
        batteryProtectionSection: "การป้องกันแบตเตอรี่",
        batteryDisableBelow: "ปิดการใช้งานเมื่อแบตเตอรี่ลดลงด้านล่าง",
        batteryNever: "ไม่เลย",
        batteryProtectionCaption: "ป้องกันไม่ให้เซสชันที่ถูกลืมทำให้แบตเตอรี่ MacBook หมด",
        clamshellSection: "ฝาปิด",
        configuring: "กำลังกำหนดค่า...",
        sudoersFailed: "ไม่สามารถเปิดโหมดฝาปิดได้ ลองอีกครั้ง",
        clamshellExplanation: "“ทำต่อไปโดยปิดฝาไว้” จะปิดโหมดสลีปโดยสมบูรณ์ในขณะที่ “ให้ตื่นอยู่เสมอ” ทำงานอยู่ และจะเปลี่ยนกลับโดยอัตโนมัติเมื่อเซสชั่นสิ้นสุดลงหรือปิดแอป ชอบใช้มันเสียบปลั๊ก",
        dimScreenOnLidCloseTitle: "หรี่แสงหน้าจอให้เป็นศูนย์",
        dimScreenOnLidCloseCaption: "หรี่แสงหน้าจอเมื่อฝาปิด และปรับความสว่างกลับคืนมาเมื่อเปิดฝา",
        scrollSection: "การเลื่อน",
        invertMouseScroll: "สลับการเลื่อนเมาส์",
        invertMouseScrollCaption: "กลับทิศทางล้อเมาส์",
        scrollTrackpadNote: "แทร็กแพดไม่ได้ถูกแตะต้อง: ช่วยให้การเลื่อนของ macOS เป็นธรรมชาติ",
        scrollActiveNow: "กำลังสลับการเลื่อนเมาส์อยู่ในขณะนี้",
        mouseNavigationActiveNow: "ปุ่มด้านข้างใช้งานอยู่ในขณะนี้",
        smoothScrollName: "เลื่อนได้อย่างราบรื่น",
        smoothScrollCaption: "เปลี่ยนแต่ละล้อของเมาส์ให้เป็นการเลื่อนที่สั้นและนุ่มนวล แทร็กแพดไม่ได้รับผลกระทบ",
        smoothScrollStepLabel: "ความเร็วขั้น",
        mouseNavigationSection: "การนำทาง",
        mouseNavigationEnable: "ใช้ปุ่มด้านข้างสำหรับย้อนกลับและไปข้างหน้า",
        mouseNavigationCaption: "เปลี่ยนปุ่มย้อนกลับและไปข้างหน้าของเมาส์ให้เป็นคำสั่งการนำทางใน Finder เบราว์เซอร์ และแอพที่รองรับ",
        middleClickSection: "คลิกตรงกลาง",
        middleClickEnable: "การคลิกด้วยสามนิ้วทำหน้าที่เป็นการคลิกตรงกลาง",
        middleClickEnableCaption: "การกดแทร็คแพดด้วยสามนิ้วทำงานเหมือนกับการคลิกล้อเมาส์: เปิดลิงก์ในแท็บใหม่ ปิดแท็บ และทุกอย่างอื่นๆ ที่ปุ่มกลางทำ",
        middleClickDragConflict: "การลากด้วยสามนิ้วของ macOS เปิดอยู่และใช้คำสั่งนิ้วเดียวกันนี้ ปิดในการตั้งค่าระบบภายใต้การช่วยสำหรับการเข้าถึง การควบคุมตัวชี้ ตัวเลือกแทร็กแพด และการคลิกตรงกลางจะทำงาน",
        middleClickTapPicker: "การแตะเบา ๆ ก็คลิกเช่นกัน",
        middleClickTapOff: "ปิด",
        middleClickTapThreeFingers: "3 นิ้ว",
        middleClickTapFourFingers: "4 นิ้ว",
        middleClickTapCaption: "การแตะเบาๆ ด้วยหลายนิ้วโดยไม่ต้องกด จะเป็นการยิงคลิกกลางด้วย การเลื่อนไม่นับ หากกำหนดแตะสามนิ้วของ macOS ให้กับ Look Up ให้ปิดเพื่อไม่ให้ทั้งคู่เริ่มทำงานพร้อมกัน",
        quickToolsTab: "แผงเครื่องมือด่วน",
        quickToolShortcutToggle: "ทางลัดระดับโลก",
        ocrName: "คัดลอกข้อความจากหน้าจอ",
        ocrCaption: "เลือกพื้นที่ของหน้าจอและคัดลอกข้อความที่รู้จักแล้วพร้อมที่จะวาง",
        ocrCopied: "คัดลอกข้อความแล้ว",
        ocrNoText: "ไม่พบข้อความ",
        colorPickerName: "ตัวเลือกสี",
        colorPickerCaption: "เลือกสีของพิกเซลบนหน้าจอแล้วคัดลอกในรูปแบบที่คุณชื่นชอบ",
        colorPickerFormatLabel: "คัดลอกรูปแบบแล้ว",
        colorPickerBareHexToggle: "คัดลอกโดยไม่มี # นำหน้า",
        colorPickerPickNow: "เลือกสี",
        micMuteName: "ปิดเสียงไมโครโฟน",
        micUnmuteName: "เปิดเสียงไมโครโฟน",
        micMuteCaption: "ตัดไมโครโฟนของ Mac ด้วยการคลิกหรือทางลัดในทุกแอพ",
        micMutedHUD: "ปิดเสียงไมโครโฟนแล้ว",
        micUnmutedHUD: "ไมโครโฟนเปิดอีกครั้ง",
        micMutePartialHUD: "ไม่สามารถปิดเสียงไมโครโฟนบางตัวได้",
        micUnmutePartialHUD: "ไมโครโฟนบางตัวยังคงปิดเสียงอยู่",
        micMuteMenuBarToggle: "แสดงในแถบเมนูขณะปิดเสียง",
        micMuteMenuBarCaption: "ไมโครโฟนที่มีเครื่องหมายกากบาทสีแดงปรากฏข้างไอคอนของแอพในแถบเมนู",
        pastePlainName: "วางเป็นข้อความธรรมดา",
        pastePlainCaption: "วางสิ่งที่คุณคัดลอกโดยไม่มีสี แบบอักษร หรือการจัดรูปแบบ ต้นฉบับจะอยู่บนคลิปบอร์ด",
        launcherName: "แผงเครื่องมือด่วน",
        launcherCaption: "แผงลอยพร้อมเครื่องมือที่คุณชื่นชอบ เรียกใช้โดยทางลัดได้จากทุกที่",
        launcherOpenNow: "เปิดแผงด่วน",
        launcherEditHint: "ใช้ปุ่มปรับแต่งเพื่อเลือก ซ่อน และลากเครื่องมือไปรอบๆ",
        launcherEmptyState: "เครื่องมือทั้งหมดถูกซ่อนอยู่ ใช้ปุ่มปรับแต่งเพื่อเพิ่มกลับ",
        launcherAddSection: "เพิ่มกลับ",
        launcherKeysHint: "ลูกศรนำทาง Enter เปิด 1 ถึง 9 เปิดโดยตรง",
        switcherSection: "ตัวสลับแอป",
        switcherEnable: "ใช้สวิตช์ Vorssaint",
        switcherEnableCaption: "สลับระหว่างแอพและหน้าต่าง รวมถึงหน้าต่างย่อเล็กสุดและหลายหน้าต่างจากแอพเดียวกัน",
        switcherUsageHint: "กดทางลัดค้างไว้เพื่อนำทาง ปล่อยเพื่อเปิดใช้งานหน้าต่าง Shift หรือ ← ย้อนกลับ; W ปิดหน้าต่าง Q ออกจากแอป Esc ยกเลิก",
        switcherNoWindows: "ไม่มีหน้าต่างที่เปิดอยู่",
        switcherIconRowMode: "แสดง %@ พร้อมไอคอนขนาดใหญ่",
        switcherIconRowModeCaption: "แสดงหนึ่งไอคอนต่อแอปโดยมีตัวอย่างหน้าต่างของแอปอยู่ด้านบน",
        switcherSimpleModeCaption: "แสดงไอคอนแอปและชื่อหน้าต่าง โดยไม่ต้องแสดงตัวอย่างหรือจับภาพหน้าจอโดยตัวสลับ",
        switcherShortcutHintApps: "แอพ",
        switcherShortcutHintWindows: "หน้าต่าง",
        switcherWindowShortcutCaption: "เปิดตัวสลับสำหรับหน้าต่างของแอปที่อยู่ด้านหน้าสุด ในขณะที่ตัวสลับแอพเปิดอยู่ ให้ข้ามไปมาระหว่างหน้าต่างของแอพที่เลือก",
        switcherTakeOverSystemShortcuts: "แทนที่ macOS ⌘Tab และ ⌘`",
        switcherTakeOverSystemShortcutsCaption: "ปิดการใช้งานแอพ macOS และทางลัดหน้าต่างที่ตรงกันเฉพาะในขณะที่ตัวสลับของ Vorssaint ทำงานอยู่ แอปที่ทำงานอยู่ทั้งหมดสามารถเข้าถึงได้",
        switcherAppearanceDelay: "ลักษณะที่ปรากฏล่าช้า",
        switcherAppearanceDelayCaption: "ต้องกดทางลัดค้างไว้นานเท่าใดก่อนที่ตัวสลับจะปรากฏขึ้น",
        switcherInstantSelection: "การเลือกทันที",
        switcherInstantSelectionCaption: "ย้ายตำแหน่งไฮไลต์และเลื่อนทันทีเมื่อคุณเรียกดูแอปและหน้าต่าง",
        switcherMergeTabs: "แสดงรายการหนึ่งรายการต่อแอป",
        switcherMergeTabsCaption: "ยุบหน้าต่างทั้งหมดของแอพเป็นรายการเดียวในตัวสลับ แทนที่จะเป็นรายการเดียวต่อหน้าต่าง",
        switcherWindowlessApps: "แอพที่ไม่มีหน้าต่างเปิดอยู่",
        switcherWindowlessAppsCaption: "เลือกแอปที่ทำงานอยู่โดยไม่มีหน้าต่างเลยให้แสดงในตัวสลับ",
        switcherWindowlessAppsOff: "อย่าแสดง",
        switcherWindowlessAppsFinder: "ตัวค้นหาเท่านั้น",
        switcherWindowlessAppsAll: "แอพทั้งหมด",
        switcherNoOpenWindow: "ไม่มีหน้าต่างที่เปิดอยู่",
        switcherOtherDesktop: "เดสก์ท็อปอื่นๆ",
        dockPreviewName: "ตัวอย่าง Dock",
        dockPreviewEnable: "ดูตัวอย่างหน้าต่างจาก Dock",
        dockPreviewEnableCaption: "วางเมาส์เหนือแอพที่เปิดอยู่บน Dock เพื่อดูหน้าต่างของแอพ จากนั้นคลิกแอพที่คุณต้องการ",
        dockPreviewCurrentSpaceOnlyCaption: "แสดงเฉพาะหน้าต่างบนเดสก์ท็อปปัจจุบันสำหรับ Dock Preview",
        dockPreviewBackgroundOpacity: "พื้นหลังแผง",
        dockPreviewBackgroundOpacityCaption: "ปรับลงเพื่อดูสิ่งที่อยู่ด้านหลังแผงเพิ่มเติม",
        dockPreviewOpenDelay: "เปิดล่าช้า",
        dockPreviewOpenDelayCaption: "ตัวชี้ต้องวางบนไอคอนนานเท่าใดก่อนที่แผงจะเปิดขึ้นมา",
        dockPreviewQuitAppOnClose: "ออกจากแอปด้วยปุ่ม ×",
        dockPreviewQuitAppOnCloseCaption: "ใน Dock Preview × ออกจากแอปทั้งหมดแทนที่จะปิดเฉพาะหน้าต่างนั้น",
        dockPreviewKeepDockVisible: "ทำให้ Dock มองเห็นได้ (ทดลอง)",
        dockPreviewKeepDockVisibleCaption: "หยุดซ่อนอัตโนมัติชั่วคราวในขณะที่เปิดดูตัวอย่าง และคืนค่าเมื่อคุณออกไป อาจปรับขนาดหน้าต่าง หากแอพถูกขัดจังหวะ ให้เปิดใหม่อีกครั้งเพื่อกู้คืน Dock",
        dockPreviewOrderByCreation: "เรียงลำดับหน้าต่างตามเวลาที่สร้าง",
        dockPreviewOrderByCreationCaption: "แสดงหน้าต่างเก่าๆ ก่อน แทนที่จะเป็นหน้าต่างที่คุณใช้ล่าสุด",
        dockClickMinimize: "คลิกไอคอน Dock เพื่อย่อขนาด",
        dockClickMinimizeCaption: "หน้าต่างของแอพที่ใช้งานอยู่จะย่อเล็กสุดเมื่อคุณคลิกไอคอน Dock คลิกอีกครั้งเพื่อนำพวกเขากลับมา",
        dockClickCycleWindows: "คลิกไอคอน Dock เพื่อวนรอบหน้าต่าง",
        dockClickCycleWindowsCaption: "คลิกไอคอน Dock ของแอปที่ใช้งานอยู่เพื่อหมุนไปตามหน้าต่าง เช่น ⌘`",
        dockPreviewActiveNow: "ใช้งานอยู่ใน Dock",
        dockPreviewDockUnavailable: "ไม่สามารถอ่านรายการ Dock ได้",
        dockPreviewAutohideBeta: "เบต้า คุณอาจพบข้อบกพร่องบางอย่าง",
        dockPreviewOpenWindow: "เปิดหน้าต่าง",
        dockPreviewCloseWindow: "ปิดหน้าต่าง",
        dockPreviewMinimizeWindow: "ย่อหน้าต่างให้เล็กสุด",
        dockPreviewRestoreWindow: "คืนค่าหน้าต่าง",
        dockPreviewPinPanel: "ดูตัวอย่างปักหมุด",
        dockPreviewUnpinPanel: "เลิกปักหมุดการแสดงตัวอย่าง",
        dockPreviewPinned: "ปักหมุดแล้ว",
        dockPreviewClosePanel: "ปิดการแสดงตัวอย่าง",
        dockPreviewPreviousWindow: "หน้าต่างก่อนหน้า",
        dockPreviewNextWindow: "หน้าต่างถัดไป",
        cutPasteName: "ตัดและวาง",
        cutPasteEnable: "ตัดและวางไฟล์ใน Finder",
        cutPasteEnableCaption: "ใช้ ⌘X เพื่อตัด และใช้ ⌘V เพื่อย้ายไฟล์และโฟลเดอร์ใน Finder",
        cutPasteShowHUD: "แสดงแผงลอย",
        cutPasteShowHUDCaption: "แสดงตัวบ่งชี้แบบลอยพร้อมกับไฟล์ที่ตัดขณะที่ Finder ทำงานอยู่",
        cutPasteHowTitle: "วิธีใช้",
        cutPasteStep1: "เลือกรายการใน Finder แล้วกด ⌘X เพื่อตัด",
        cutPasteStep2: "เปิดโฟลเดอร์ปลายทางแล้วกด ⌘V เพื่อย้ายไปที่นั่น",
        cutPasteTextNote: "ในช่องข้อความ (เช่น เมื่อเปลี่ยนชื่อ) ⌘X และ ⌘V ยังคงทำงานตามปกติ",
        cutPasteActiveNow: "พร้อมตัดใน Finder",
        cutPasteAutomationNote: "ครั้งแรกที่ macOS จะขออนุญาตเพื่อควบคุม Finder",
        cutReadyTitle: "ตัด",
        cutReadyHint: "ในโฟลเดอร์ปลายทางที่จะย้าย",
        cutCancel: "ยกเลิกการตัด",
        cutDoneTitle: "ย้ายแล้ว!",
        cutMovedSingular: "ย้ายแล้ว 1 รายการ",
        cutMovedPluralFormat: "ย้าย %d รายการแล้ว",
        cutSomeFailed: "ไม่สามารถย้ายบางรายการได้",
        cutMovingTitle: "กำลังย้าย...",
        cutMovingCountFormat: "%d จาก %d",
        autoQuitName: "ปิดเทอมแล้ว",
        autoQuitEnable: "ออกจากแอพเมื่อหน้าต่างสุดท้ายปิดลง",
        autoQuitEnableCaption: "การปิดหน้าต่างสุดท้ายของแอปจะเป็นการปิดหน้าต่างนั้นด้วย",
        autoQuitActiveNow: "ใช้งานอยู่ในขณะนี้",
        autoQuitHowTitle: "มันทำงานอย่างไร",
        autoQuitStep1: "ปิดหน้าต่างสุดท้ายของแอป (⌘W หรือปุ่มสีแดง)",
        autoQuitStep2: "แอปปิดการทำงานเอง “บันทึกการเปลี่ยนแปลง?” กล่องโต้ตอบยังคงปรากฏขึ้น",
        autoQuitPredictableNote: "แอพที่ปกติทำงานโดยไม่มีหน้าต่างจะไม่มีวันปิด",
        autoQuitOngoingWorkNote: "แอพบางแอพจะปิดหน้าต่างสุดท้ายในขณะที่ทำงานต่อไป เช่น เครื่องบันทึกหน้าจอเมื่อเริ่มจับภาพ สิ่งเหล่านี้ก็จะเลิกใช้เช่นกัน เว้นแต่ว่าจะอยู่ในรายการข้อยกเว้น",
        autoQuitExceptionsTitle: "ข้อยกเว้น",
        autoQuitExceptionsCaption: "แอพในรายการนี้ยังคงเปิดอยู่แม้ว่าจะไม่มีหน้าต่างก็ตาม",
        autoQuitExceptionsEmpty: "ไม่มีข้อยกเว้น",
        autoQuitAddApp: "เพิ่มแอป...",
        uninstallerName: "โปรแกรมถอนการติดตั้ง",
        uninstallerEnableCaption: "ลบแอปพร้อมกับแคช การตั้งค่า บันทึก และสิ่งที่เหลืออยู่ที่ทิ้งไว้",
        uninstallerStep1: "ลากแอปไปที่การตั้งค่า หรือเลือกจากรายการ",
        uninstallerStep2: "ตรวจสอบไฟล์ที่พบและพื้นที่ที่ใช้",
        uninstallerStep3: "ย้ายสิ่งที่คุณต้องการไปที่ถังขยะ ไม่มีสิ่งใดถูกลบอย่างถาวร",
        uninstallerMenuItem: "ถอนการติดตั้งแอป...",
        uninstallerDropTitle: "ลากแอปมาที่นี่",
        uninstallerDropSubtitle: "หรือเลือกอันที่จะสแกน",
        uninstallerChoose: "เลือกแอป...",
        uninstallerPickerTitle: "เลือกแอป",
        uninstallerPickerSearch: "ค้นหาแอพ",
        uninstallerPickerEmpty: "ไม่พบแอป",
        uninstallerEmptyNote: "ไม่มีสิ่งใดถูกลบออกหากไม่มีการยืนยันจากคุณ",
        uninstallerFDANote: "ให้สิทธิ์การเข้าถึงดิสก์แบบเต็มเพื่อการสแกนที่ละเอียดยิ่งขึ้น",
        uninstallerFDAGrant: "ให้สิทธิ์การเข้าถึง...",
        uninstallerFDAHint: "เปิด Vorssaint ในรายการ หากไม่มีอยู่ ให้คลิก + และเลือก Vorssaint จาก Applications การเข้าถึงจะมีผลหลังจากที่คุณเปิดแอปอีกครั้งเท่านั้น",
        uninstallerFDARelaunch: "เปิดตัวใหม่ตอนนี้",
        uninstallerScanning: "กำลังสแกนไฟล์...",
        uninstallerRemoving: "กำลังย้ายไปถังขยะ...",
        uninstallerFoundTitle: "พบ",
        uninstallerSelectedFormat: "เลือก %1$d จาก %2$d รายการ",
        uninstallerRemove: "ย้ายไปที่ถังขยะ",
        uninstallerCancel: "ยกเลิก",
        uninstallerConfirmationExpired: "การยืนยันนี้ใช้ไม่ได้อีกต่อไป ตรวจสอบรายการปัจจุบันและยืนยันอีกครั้ง",
        uninstallerDoneTitle: "เสร็จแล้ว!",
        uninstallerFreedFormat: "คืนพื้นที่ได้ %@",
        uninstallerSomeFailed: "บางรายการไม่สามารถย้ายลงถังขยะได้",
        uninstallerFailedNeedsFDA: "ข้อมูลแอปที่แซนด์บ็อกซ์สามารถย้ายได้ด้วยการเข้าถึงดิสก์แบบเต็มเท่านั้น รหัสผ่านผู้ดูแลระบบไม่สามารถใช้งานได้",
        uninstallerFailedMoreFormat: "และ %d เพิ่มเติม",
        uninstallerAnother: "ถอนการติดตั้งอันอื่น",
        uninstallerCatApp: "แอปพลิเคชัน",
        uninstallerCatSupport: "สนับสนุน",
        uninstallerCatCaches: "แคช",
        uninstallerCatPreferences: "การตั้งค่า",
        uninstallerCatContainers: "ตู้คอนเทนเนอร์",
        uninstallerCatLogs: "บันทึก",
        uninstallerCatState: "สถานะที่บันทึกไว้",
        uninstallerCatOther: "อื่นๆ",
        uninstallerCommandBarBrowseTitle: "ถอนการติดตั้งแอปพลิเคชัน",
        uninstallerCommandBarToggle: "แสดงในแถบคำสั่ง",
        uninstallerCommandBarCaption: "เลือกและถอนการติดตั้งแอพในแถบคำสั่ง",
        uninstallerCommandBarFinderTitle: "ถอนการติดตั้งแอพที่เลือกใน Finder",
        uninstallerSelectionUnavailable: "เลือกแอพที่สามารถลบออกได้ใน Finder หรือเลือกแอพอื่นจากรายการ",
        urlCleanerName: "ล้าง URL",
        urlCleanerEnable: "ทำความสะอาด URL ขณะที่คุณคัดลอก",
        urlCleanerEnableCaption: "ลบพารามิเตอร์การติดตามออกจากลิงก์ทันทีที่มาถึงคลิปบอร์ด",
        urlCleanerActiveNow: "ใช้งานอยู่ในขณะนี้",
        urlCleanerManualTitle: "ทำความสะอาดเลย",
        urlCleanerInputPlaceholder: "วาง URL",
        urlCleanerOutputPlaceholder: "URL ที่ชัดเจนจะปรากฏที่นี่",
        urlCleanerCleanButton: "ทำความสะอาด",
        urlCleanerPasteButton: "วาง",
        urlCleanerCopyButton: "คัดลอก",
        urlCleanerClearButton: "ล้างข้อมูลในช่อง",
        urlCleanerNoURL: "วาง URL ที่ถูกต้อง",
        urlCleanerNoChange: "ไม่มีอะไรจะทำความสะอาด",
        urlCleanerCleaned: "ล้าง URL แล้ว",
        urlCleanerCopied: "คัดลอกแล้ว",
        urlCleanerLocalNote: "ท้องถิ่น. ไม่มีเครือข่าย",
        homebrewName: "Homebrew",
        homebrewEnableCaption: "ค้นหา ติดตั้ง และลบสูตรและถัง",
        homebrewMissingTitle: "ไม่พบโฮมบรูว์",
        homebrewMissingBody: "Vorssaint สามารถเปิด Terminal ได้ด้วยโปรแกรมติดตั้ง Homebrew อย่างเป็นทางการ Terminal จะแสดงขั้นตอนและถามรหัสผ่านของคุณหากจำเป็น",
        homebrewInstallHomebrew: "ติดตั้งโฮมบรูว์",
        homebrewInstallHomebrewCaption: "เมื่อ Terminal เสร็จสิ้น ให้กลับมาที่นี่แล้วคลิก Refresh",
        homebrewInstallHomebrewOpened: "ตัวติดตั้งเปิดใน Terminal",
        homebrewShellSetupTitle: "เสร็จสิ้นการตั้งค่าเทอร์มินัล",
        homebrewShellSetupBody: "ติดตั้ง Homebrew แล้ว แต่ Terminal อาจไม่พบคำสั่งชง Vorssaint สามารถเปิด Terminal ได้ด้วยคำสั่งตั้งค่า",
        homebrewShellSetupButton: "ตั้งค่าเทอร์มินัล",
        homebrewShellSetupOpened: "คำสั่งเปิดใน Terminal จากนั้นกลับมาที่นี่แล้วคลิกรีเฟรช",
        homebrewRefresh: "รีเฟรช",
        homebrewCheckPackages: "ตรวจสอบแพ็คเกจ",
        homebrewTrustTitle: "แตะยังไม่น่าเชื่อถือ",
        homebrewTrustCaption: "ตอนนี้ Homebrew จะขอให้คุณยืนยันก่อนที่จะใช้การแตะของบุคคลที่สาม เชื่อถือ %@ เพื่อดำเนินการต่อ",
        homebrewTrustButton: "ไว้วางใจและดำเนินการต่อ",
        homebrewSearchPlaceholder: "ค้นหาแพ็คเกจ",
        homebrewKeyboardHint: "Space หรือ Return จะปิดแผง macOS ใช้ปุ่มค้นหา",
        homebrewSearchButton: "ค้นหา",
        homebrewSearchResults: "ผลลัพธ์",
        homebrewInstalled: "ติดตั้งแล้ว",
        homebrewAll: "ทั้งหมด",
        homebrewFormulas: "สูตร",
        homebrewCasks: "ถัง",
        homebrewNoPackages: "ไม่พบแพ็คเกจ",
        homebrewDependencies: "การพึ่งพาอาศัยกัน",
        homebrewGroupDependencies: "การพึ่งพากลุ่ม",
        homebrewNoSelection: "เลือกแพ็คเกจที่ติดตั้งหรือค้นหาแพ็คเกจใหม่",
        homebrewDetailsTitle: "รายละเอียดแพ็คเกจ",
        homebrewInstall: "ติดตั้ง",
        homebrewUninstall: "ถอนการติดตั้ง",
        homebrewUpgrade: "อัปเดต",
        homebrewUpgradeAll: "อัพเดททั้งหมดครับ",
        homebrewUpdateHomebrew: "อัพเดตโฮมบรูว์",
        homebrewAllPackages: "แพคเกจ",
        homebrewOpenTerminal: "เปิดเทอร์มินัล",
        homebrewCancelOperation: "ยกเลิก",
        homebrewClearLog: "ล้างบันทึก",
        homebrewLogTitle: "บันทึก",
        homebrewVersion: "เวอร์ชัน",
        homebrewDescription: "พิมพ์",
        homebrewHomepage: "เปิดเว็บไซต์",
        homebrewPopularity: "ความนิยม",
        homebrewPopularityFormat: "ติดตั้ง %1$@ ครั้ง ใน %2$@ วันที่ผ่านมา",
        homebrewInstalledBadge: "ติดตั้งแล้ว",
        homebrewNotInstalledBadge: "ไม่ได้ติดตั้ง",
        homebrewUpdates: "รายการอัปเดต",
        homebrewUpdateAvailableBadge: "อัปเดตพร้อมใช้งาน",
        homebrewLatestVersion: "ล่าสุด",
        homebrewConfirmInstallTitle: "ติดตั้งกับ Homebrew หรือไม่?",
        homebrewConfirmInstallBodyFormat: "Homebrew จะดาวน์โหลดและติดตั้ง %@ การดำเนินการนี้อาจติดตั้งส่วนประกอบที่จำเป็นด้วย",
        homebrewConfirmUninstallTitle: "ถอนการติดตั้งด้วย Homebrew หรือไม่",
        homebrewConfirmUninstallBodyFormat: "Homebrew จะถอนการติดตั้ง %@ ไฟล์การกำหนดค่าอาจยังคงอยู่ในระบบ",
        homebrewConfirmUpgradeTitle: "อัพเดตด้วย Homebrew หรือไม่?",
        homebrewConfirmUpgradeBodyFormat: "Homebrew จะดาวน์โหลดและอัปเกรด %@ เป็นเวอร์ชันล่าสุด",
        homebrewConfirmUpgradeAllTitle: "อัปเดตทั้งหมดด้วย Homebrew หรือไม่",
        homebrewConfirmUpgradeAllBody: "Homebrew จะดาวน์โหลดและใช้เวอร์ชันล่าสุดสำหรับแพ็คเกจที่มีการอัพเดต การพึ่งพาอาจได้รับการอัปเดตด้วย",
        homebrewConfirmUpdateHomebrewTitle: "อัพเดตโฮมบรูว์?",
        homebrewConfirmUpdateHomebrewBody: "Homebrew จะดึงข้อมูลล่าสุดแล้วโหลดแพ็คเกจของคุณใหม่",
        homebrewTerminalFallback: "การดำเนินการนี้ต้องการให้ Terminal ถามรหัสผ่านผู้ดูแลระบบ Vorssaint ไม่บันทึกรหัสผ่าน",
        homebrewLoading: "กำลังโหลด...",
        homebrewSearchEmpty: "ไม่มีผลลัพธ์",
        homebrewOperationInstallFormat: "กำลังติดตั้ง %@",
        homebrewOperationUninstallFormat: "กำลังถอนการติดตั้ง %@",
        homebrewOperationUpgradeFormat: "กำลังอัปเกรด %@",
        homebrewOperationUpgradeAll: "กำลังอัพเดตแพ็คเกจ",
        homebrewOperationUpdateHomebrew: "กำลังอัปเดต Homebrew",
        homebrewOperationInstalledFormat: "ติดตั้ง %@ สำเร็จแล้ว",
        homebrewOperationUninstalledFormat: "ถอนการติดตั้ง %@ สำเร็จแล้ว",
        homebrewOperationUpgradedFormat: "อัปเกรด %@ สำเร็จแล้ว",
        homebrewOperationUpgradedAll: "แพ็คเกจอัพเดทแล้ว",
        homebrewOperationUpdatedHomebrew: "อัปเดตโฮมบรูว์แล้ว",
        homebrewOperationFailedFormat: "การดำเนินการกับ %@ ล้มเหลว",
        homebrewOperationCancelled: "การดำเนินการถูกยกเลิก",
        homebrewOperationPreparing: "กำลังเตรียมการ…",
        homebrewOperationDownloading: "กำลังดาวน์โหลด…",
        homebrewOperationInstalling: "กำลังติดตั้ง…",
        homebrewOperationUninstalling: "กำลังถอนการติดตั้ง…",
        homebrewOperationUpgrading: "กำลังอัปเกรด…",
        homebrewOperationFinalizing: "กำลังเสร็จสิ้น…",
        homebrewOperationRefreshing: "กำลังรีเฟรช…",
        homebrewOperationTerminal: "ดำเนินการต่อในเทอร์มินัล",
        homebrewOperationElapsedFormat: "เสร็จสิ้นใน %@",
        homebrewOperationShowDetails: "แสดงรายละเอียด",
        homebrewOperationHideDetails: "ซ่อนรายละเอียด",
        homebrewOperationTechnicalLog: "รายละเอียดทางเทคนิค",
        homebrewOperationProgressUnknown: "Homebrew ยังไม่ได้รายงานเปอร์เซ็นต์",
        mediaName: "สื่อ",
        mediaEnableCaption: "บีบอัดวิดีโอ แปลงและประมวลผลรูปภาพ สร้าง GIF และแยกข้อความในเครื่อง",
        mediaLocalNote: "ท้องถิ่น. ไม่มีเครือข่าย",
        mediaToolVideo: "วีดีโอ",
        mediaToolGIF: "กิฟ",
        mediaToolImage: "ภาพ",
        mediaToolText: "ข้อความ",
        mediaSelectFile: "เลือกไฟล์",
        mediaDropHint: "วางไฟล์ที่นี่หรือคลิกเพื่อเลือกหนึ่งไฟล์",
        mediaOutput: "เอาท์พุต",
        mediaOutputAutomatic: "อัตโนมัติ",
        mediaChooseOutput: "ปลายทาง",
        mediaStartVideo: "บีบอัดวิดีโอ",
        mediaStartGIF: "ทำ GIF",
        mediaStartImage: "ประมวลผลภาพ",
        mediaStartConvertPDF: "แปลงเป็น PDF",
        mediaStartText: "แยกข้อความ",
        mediaCancel: "ยกเลิก",
        mediaStartTime: "เริ่ม",
        mediaEndTime: "จบ",
        mediaQuality: "การบีบอัด",
        mediaCompressionLow: "ต่ำ",
        mediaCompressionMedium: "ปานกลาง",
        mediaCompressionHigh: "สูง",
        mediaCompressionLowDescription: "คุณภาพสูง ขนาดไฟล์ใหญ่",
        mediaCompressionMediumDescription: "คุณภาพและขนาดไฟล์ที่สมดุล",
        mediaCompressionHighDescription: "คุณภาพต่ำ ขนาดไฟล์เล็ก",
        mediaMaxSize: "ขนาด",
        mediaSizingResolution: "ปณิธาน",
        mediaSizingFileSize: "ขนาดไฟล์",
        mediaTargetSize: "ขนาดเป้าหมาย",
        mediaTargetSizeHint: "ความละเอียดจะปรับให้อยู่ภายใต้ขีดจำกัด",
        mediaErrorTargetTooSmall: "ขนาดเป้าหมายเล็กเกินไปสำหรับคลิปนี้ ตัดแต่งหรือเพิ่มขีดจำกัด",
        mediaMegabytesSuffix: "เอ็มบี",
        mediaWidth: "ความกว้าง",
        mediaFPS: "เฟรมต่อวินาที",
        mediaKeepAudio: "เก็บเสียง",
        mediaCodec: "ตัวแปลงสัญญาณ",
        mediaFormat: "รูปแบบ",
        mediaStripMetadata: "ลบข้อมูลเมตา",
        mediaLoopGIF: "วนซ้ำ GIF",
        mediaOCRMode: "โอซีอาร์",
        mediaOCRAccurate: "แม่นยำ",
        mediaOCRFast: "เร็ว",
        mediaLanguageCorrection: "การแก้ไขภาษา",
        mediaTextOutputNote: "ข้อความที่แยกออกมาสามารถคัดลอกและบันทึกเป็น TXT ได้",
        mediaRunning: "กำลังประมวลผล",
        mediaCompleted: "เสร็จสิ้น",
        mediaCancelled: "ยกเลิก.",
        mediaOpenInFinder: "แสดง",
        mediaCopyText: "คัดลอกข้อความ",
        mediaRunAgain: "วิ่งอีกครั้ง",
        mediaEmptyText: "ไม่พบข้อความ",
        mediaResultSavedFormat: "บันทึกเป็น %@",
        mediaResultSizeFormat: "%@ ถึง %@",
        mediaResultGrewCaption: "ไฟล์ที่แปลงออกมามีขนาดใหญ่กว่าเดิม",
        mediaErrorNoFile: "เลือกไฟล์ก่อน",
        mediaErrorNoVideo: "ไฟล์นี้ไม่มีแทร็กวิดีโอ",
        mediaErrorSameOutput: "เลือกปลายทางที่แตกต่างจากไฟล์ต้นฉบับ",
        mediaErrorUnsupported: "รูปแบบไม่รองรับโดย macOS",
        shelfName: "ชั้นวาง",
        shelfEnable: "พื้นที่ชั่วคราวสำหรับการลากไฟล์",
        shelfEnableCaption: "จุดลอยตัวสำหรับรวบรวมไฟล์ รูปภาพ และข้อความ จากนั้นลากไปที่ไหนก็ได้ในภายหลัง",
        shelfHowTitle: "วิธีใช้",
        shelfStep1: "เปิดโดยใช้ทางลัดหรือโดยการเขย่าเมาส์ระหว่างการลาก",
        shelfStep2: "วางไฟล์ รูปภาพ ลิงก์ หรือข้อความลงไปเพื่อเก็บไว้",
        shelfStep3: "ลากแต่ละรายการกลับออกไปที่แอพใดก็ได้เมื่อคุณต้องการ",
        shelfShakeToggle: "เปิดโดยการเขย่าเมาส์ขณะลาก",
        shelfShakeCaption: "เขย่าพอยน์เตอร์อย่างรวดเร็วในขณะที่ถือไอเท็มไว้เพื่อเรียกออกมาใกล้กับเคอร์เซอร์",
        shelfDropZoneToggle: "เก็บไฟล์ที่ลากไว้ในแถบเมนู",
        shelfDropZoneCaption: "ขณะที่คุณลากไฟล์ ชั้นวางจะปรากฏใต้ไอคอนแถบเมนู สิ่งที่คุณทำหล่นจะถูกเก็บไว้ตรงนั้น ในปุ่มที่คุณย่อและเปิดด้วยการคลิกที่จะหายไปเมื่อชั้นวางว่างเปล่า",
        shelfDropZoneCaptionTopCenter: "ขณะที่คุณลากไฟล์ ชั้นวางจะแสดงเป็นป้ายที่ตรงกลางด้านบนของหน้าจอ สิ่งที่คุณทำหล่นจะถูกเก็บไว้ตรงนั้น ในป้ายที่คุณเปิดด้วยการคลิก ซึ่งจะหายไปเมื่อชั้นวางว่างเปล่า",
        shelfDropZoneLabel: "วางที่นี่",
        shelfDockPlacement: "ตำแหน่ง",
        shelfDockMenuBar: "ใต้ไอคอนแถบเมนู",
        shelfDockTopCenter: "ตรงกลางด้านบนของหน้าจอ",
        shelfDockIslandNote: "Dynamic Island จะรักษาจุดศูนย์กลางด้านบนไว้ในขณะที่เปิดอยู่",
        shelfCollapse: "ทรุด",
        shelfBehaviorTitle: "หลังการใช้งาน",
        shelfCloseAfterDrop: "ปิดหลังจากเข้าสู่แอปอื่น",
        shelfCloseAfterDropCaption: "ปิดชั้นวางเมื่อปลายทางยอมรับสินค้า หมุดในแผงช่วยให้เปิดอยู่",
        shelfRemoveAfterDrop: "ลบรายการหลังจากวาง",
        shelfRemoveAfterDropCaption: "รายการที่แอปอื่นยอมรับจะออกจากชั้นวางแล้ว ปิดการทำงานนี้เพื่อเก็บสำเนาไว้ที่นั่น รายการที่ปักหมุดจะยังคงอยู่เสมอ",
        shelfExclusionsTitle: "ข้อยกเว้นอัตโนมัติ",
        shelfExclusionsEmpty: "ไม่มีการเพิ่มแอป",
        shelfExclusionsCaption: "เขย่าและแถบเมนูดรอปโซนจะปิดอยู่สำหรับการลากที่เริ่มต้นในแอปเหล่านี้ ทางลัดและเปิดตอนนี้ยังคงใช้งานได้",
        shelfPin: "เปิดต่อครับ",
        shelfUnpin: "อนุญาตให้ปิดหลังการใช้งาน",
        extraBrightnessName: "ความสว่างเป็นพิเศษ",
        extraBrightnessCaption: "ใช้พื้นที่ส่วนหัวของ HDR ของจอแสดงผลเพื่อให้ผ่านความสว่างสูงสุด ใช้แบตเตอรี่มากขึ้นและ Mac ก็สามารถทำงานได้อย่างอบอุ่น",
        extraBrightnessLevelLabel: "ความเข้ม",
        extraBrightnessUnsupported: "มีเฉพาะบนจอแสดงผล XDR เช่นบน MacBook Pro รุ่น 14 และ 16 นิ้ว",
        shelfHotkeyLabel: "ทางลัด",
        shelfOpenNow: "เปิดแล้ว",
        shelfNoPermission: "ไม่จำเป็นต้องได้รับอนุญาต",
        shelfMenuItem: "เปิดชั้นวาง",
        shelfTitle: "ชั้นวาง",
        shelfEmpty: "ลากรายการมาที่นี่",
        shelfClearAll: "เคลียร์ทั้งหมด",
        shelfRemoveSelected: "ลบที่เลือกไว้",
        shelfSelectedFormat: "เลือก %d รายการ",
        shelfHint: "คลิกเพื่อเลือก ลากออกเพื่อใช้หรือคลิกขวาเพื่อดำเนินการเพิ่มเติม",
        shelfItemImage: "ภาพ",
        shelfTooltipItemsFormat: "%d รายการ",
        shelfTooltipItemsFew: "%d รายการ",
        shelfTooltipImageSingular: "__ภาพ FMT0__ (%d)",
        shelfTooltipImageFew: "__ภาพ FMT0__ (%d)",
        shelfTooltipImagePlural: "__ภาพ FMT0__ (%d)",
        shelfTooltipFileSingular: "ไฟล์ %d",
        shelfTooltipFileFew: "%d ไฟล์",
        shelfTooltipFilePlural: "%d ไฟล์",
        shelfTooltipNoteSingular: "%d หมายเหตุ",
        shelfTooltipNoteFew: "%d หมายเหตุ",
        shelfTooltipNotePlural: "%d หมายเหตุ",
        shelfTooltipLinkSingular: "ลิงก์ %d",
        shelfTooltipLinkFew: "ลิงก์ %d",
        shelfTooltipLinkPlural: "ลิงก์ %d",
        shelfActionOpen: "เปิด",
        shelfActionOpenWith: "เปิดด้วย",
        shelfActionShare: "แบ่งปัน",
        shelfActionPin: "เข็มหมุด",
        shelfActionUnpin: "เลิกปักหมุด",
        breakdownMeasuring: "กำลังวัด...",
        mixerSection: "เครื่องผสมระดับเสียง",
        mixerEmpty: "แอพที่ใช้เสียงจะแสดงที่นี่",
        mixerUnavailable: "ใช้งานได้บน macOS 14.4 และใหม่กว่า",
        mixerPermissionBody: "หากต้องการปรับระดับเสียงต่อแอป ให้อนุญาต \"การบันทึกเสียงหน้าจอและระบบ\" ในการตั้งค่าระบบ เสียงจะไม่ถูกบันทึก",
        mixerResetTooltip: "รีเซ็ตเป็น 100%",
        mixerOutputDefault: "ค่าเริ่มต้น",
        mixerOutputCurrent: "ปัจจุบัน",
        mixerOutputUnavailable: "เอาต์พุตไม่พร้อมใช้งาน",
        mixerOutputFallback: "ใช้ค่าเริ่มต้นจนกว่าอุปกรณ์นี้จะกลับมา",
        mixerBypassedCaption: "แอปนี้จัดการเสียงของตัวเอง",
        mixerOutputTooltip: "เลือกเอาต์พุต",
        mixerSystemOutputTitle: "เอาท์พุต",
        mixerSystemOutputNoDevices: "ไม่พบผลลัพธ์",
        mixerSystemOutputTooltip: "เลือกเอาต์พุตของระบบ",
        mixerSystemOutputErrorFormat: "ไม่สามารถสลับได้: %@",
        mixerLowerOnHeadphonesDisconnect: "ลดระดับเสียงลงเมื่อหูฟังตัดการเชื่อมต่อ",
        mixerLowerOnHeadphonesDisconnectCaption: "ปรับเอาต์พุตเมื่อหูฟังแบบมีสายหรือบลูทูธตัดการเชื่อมต่อ",
        mixerHeadphonesDisconnectVolume: "ระดับเสียงหลังจากตัดการเชื่อมต่อ",
        preciseVolumeRollerEnable: "ใช้ขั้นตอนที่มีระดับเสียงปลีกย่อย",
        preciseVolumeRollerCaption: "เปลี่ยนวงล้อปรับระดับเสียงและปุ่มปรับระดับเสียงให้เป็นขั้นปรับระดับเสียงของระบบที่เล็กลง",
        preciseVolumeRollerTapFailed: "ไม่สามารถฟังปุ่มปรับระดับเสียงได้",
        soundOutputSwitcherTitle: "ตัวสลับเอาต์พุต",
        soundOutputSwitcherEnable: "สลับเอาต์พุตด้วยทางลัด",
        soundOutputSwitcherCaption: "เลือกเอาต์พุตและใช้ทางลัดเพื่อย้ายไปยังเอาต์พุตถัดไปที่มี",
        soundOutputSwitcherDevices: "เอาท์พุตในวงจร",
        soundOutputSwitcherNoAvailableSelection: "เลือกเอาต์พุตที่มีอยู่อย่างน้อยหนึ่งรายการ",
        mixerInputTitle: "ไมโครโฟน",
        mixerInputNoDevices: "ไม่พบไมโครโฟน",
        mixerInputUnavailable: "ไมโครโฟนไม่พร้อมใช้งาน",
        mixerInputFallback: "ใช้ค่าเริ่มต้นจนกว่าไมโครโฟนนี้จะกลับมา",
        mixerInputTooltip: "เลือกไมโครโฟน",
        mixerInputErrorFormat: "ข้อผิดพลาดอินพุตของมิกเซอร์: %@",
        mixerVisibleApps: "แอพในรายการ",
        mixerAllShown: "ทั้งหมด",
        mixerHiddenCountLabel: "ที่ซ่อนอยู่",
        mixerHideFromList: "ซ่อนจากรายการ",
        audioPrioritySection: "ลำดับความสำคัญของเสียง",
        audioPriorityOutputEnable: "สลับไปยังเอาต์พุตที่มีลำดับความสำคัญสูงสุดโดยอัตโนมัติ",
        audioPriorityInputEnable: "สลับไปใช้ไมโครโฟนที่มีลำดับความสำคัญสูงสุดโดยอัตโนมัติ",
        audioPriorityOutputList: "ลำดับความสำคัญของเอาต์พุต",
        audioPriorityInputList: "ลำดับความสำคัญของไมโครโฟน",
        audioPriorityMoveUp: "เลื่อนขึ้น",
        audioPriorityMoveDown: "เลื่อนลง",
        audioPriorityUnavailable: "ไม่พร้อมใช้งาน",
        audioPriorityCurrent: "ปัจจุบัน",
        audioPriorityCaption: "อุปกรณ์ถูกเลือกตามลำดับความสำคัญ เมื่อเชื่อมต่ออุปกรณ์ที่มีลำดับความสำคัญสูงกว่า อุปกรณ์จะเปิดใช้งาน เมื่ออันที่ใช้งานอยู่ยกเลิกการเชื่อมต่อ อันถัดไปที่มีอยู่จะเข้ามาแทนที่",
        updatesSection: "รายการอัปเดต",
        autoCheckToggle: "ตรวจสอบการอัปเดตโดยอัตโนมัติ",
        includeBetaUpdatesToggle: "รับการอัปเดตเบต้า",
        includeBetaUpdatesCaption: "เวอร์ชันเบต้ามีคุณสมบัติในการพัฒนาและอาจมีจุดบกพร่องหรือการทำงานที่ไม่สมบูรณ์",
        betaBadgeLabel: "เบต้า",
        checkNowButton: "ตรวจสอบทันที",
        updateChecking: "กำลังตรวจสอบ...",
        updateUpToDate: "คุณใช้เวอร์ชันล่าสุด",
        updateAvailablePrefix: "มีการอัปเดต:",
        updateInstallButton: "ดาวน์โหลดและติดตั้ง",
        updateDownloading: "กำลังดาวน์โหลดอัปเดต...",
        updateInstalling: "กำลังติดตั้งและรีสตาร์ท...",
        updateFailedPrefix: "ไม่สามารถตรวจสอบ:",
        updateLastChecked: "ตรวจสอบครั้งล่าสุด:",
        updateNotifyTitle: "อัพเดทวอร์สเซนต์",
        updateInstallFailedBody: "ดาวน์โหลดการอัปเดตแล้วแต่ไม่สามารถใช้งานได้ ดาวน์โหลดเวอร์ชันล่าสุดจากหน้าเผยแพร่ GitHub และลากแอปไปไว้เหนือเวอร์ชันปัจจุบัน",
        updateNeedsApplicationsTitle: "ย้าย Vorssaint ไปที่แอปพลิเคชัน",
        updateNeedsApplicationsBody: "แอปกำลังทำงานจากตำแหน่งที่ไม่สามารถอัปเดตได้ เช่น ดิสก์อิมเมจหรือตำแหน่งระบบชั่วคราว ลาก Vorssaint ไปที่โฟลเดอร์ Applications แล้วเปิดจากที่นั่นแล้วลองอีกครั้ง",
        menuCheckUpdates: "ตรวจสอบการอัปเดต...",
        permissionRequired: "ต้องได้รับอนุญาต",
        permissionAccessibility: "การเข้าถึง",
        permissionScreenRecording: "การบันทึกหน้าจอ",
        permissionGranted: "ได้รับ",
        permissionMissing: "ไม่ได้รับ",
        permissionOpenSettings: "เปิดการตั้งค่าระบบ...",
        permissionRequest: "ให้สิทธิ์การเข้าถึง",
        permissionRestartNote: "macOS อาจขอให้เปิดแอปอีกครั้งหลังจากอนุญาต",
        secureInputTitle: "Secure Input กำลังทำงาน",
        secureInputHeldFormat: "%@ กำลังใช้งาน Secure Input",
        secureInputUnattributed: "ไม่สามารถระบุแอปที่เปิดใช้งาน Secure Input",
        secureInputUnidentified: "แอปที่ไม่รู้จักกำลังเปิดใช้งาน Secure Input",
        secureInputRevealFormat: "แสดง %@ ใน Finder",
        aboutDescription: "ศูนย์กลางยูทิลิตี้สำหรับ Mac ของคุณ\nพลังงาน การตรวจสอบระบบ การเลื่อน และตัวสลับหน้าต่าง อยู่ในแถบเมนูโดยตรง",
        versionPrefix: "เวอร์ชัน",
        reviewIntro: "ทบทวนบทนำ",
        reviewHighlights: "รีวิวไฮไลท์",
        viewOnGitHub: "ดูบน GitHub",
        obContinue: "ดำเนินการต่อ",
        obBack: "ย้อนกลับ",
        obSkipStep: "ข้ามขั้นตอนนี้",
        obStart: "เปิดวอร์สแซงต์",
        obStepWelcomeTitle: "ยินดีต้อนรับสู่ Vorssaint",
        obStepWelcomeBody: "ยูทิลิตี้แถบเมนูรอบคอบที่ทำให้ macOS ในชีวิตประจำวันมีประโยชน์มากขึ้น",
        obWelcomeBullet1Title: "พลังงานอยู่ภายใต้การควบคุม",
        obWelcomeBullet1Body: "ให้ Mac ตื่นตัวได้นานเท่าที่คุณต้องการ แม้จะปิดฝาอยู่ก็ตาม",
        obWelcomeBullet2Title: "มุมมองที่ชัดเจนของระบบ",
        obWelcomeBullet2Body: "อุณหภูมิ CPU, GPU และแบตเตอรี่ การใช้งานฮาร์ดแวร์ และแรงกดดันของหน่วยความจำแบบเรียลไทม์",
        obWelcomeBullet3Title: "เมาส์และหน้าต่าง ในแบบของคุณ",
        obWelcomeBullet3Body: "การเลื่อนเมาส์แบบย้อนกลับและตัวสลับหน้าต่างพร้อมภาพขนาดย่อ",
        obLanguageLabel: "ภาษา",
        obStepAccessibilityTitle: "การเข้าถึง",
        obStepAccessibilityBody: "จำเป็นต้องสลับการเลื่อนเมาส์และเพื่อให้ตัวสลับหน้าต่างตอบสนองต่อแป้นพิมพ์",
        obAccessibilityWhy: "แอปจะเฝ้าดูเฉพาะล้อเลื่อนของเมาส์และทางลัดของตัวสลับเท่านั้น ไม่มีการบันทึกหรือส่งไปที่ใด",
        obStepRecordingTitle: "การบันทึกหน้าจอ",
        obStepRecordingBody: "อนุญาตให้ตัวสลับแสดงภาพขนาดย่อของหน้าต่างจริงแทนที่จะเป็นไอคอนเท่านั้น",
        obRecordingWhy: "รูปย่อจะถูกสร้างขึ้นทันที อยู่ในความทรงจำ และไม่ต้องละทิ้ง Mac ของคุณ หากไม่มีมัน ตัวสลับจะยังคงใช้งานได้กับไอคอน",
        obStepMonitorTitle: "การตรวจสอบระบบ",
        obStepMonitorBody: "แผงควบคุมจะแสดงอุณหภูมิ CPU, GPU และแบตเตอรี่ การใช้งานฮาร์ดแวร์ และความดันหน่วยความจำ",
        obMonitorNoPermission: "ไม่จำเป็นต้องได้รับอนุญาต เซ็นเซอร์จะถูกอ่านโดยตรงจากระบบ",
        obStepOptionalTitle: "คุณสมบัติเสริม",
        obStepOptionalBody: "เปิดสิ่งที่คุณต้องการใช้ตอนนี้ ทุกอย่างสามารถเปลี่ยนแปลงได้ในภายหลังในการตั้งค่า",
        obStepStatusTitle: "ตรวจสุขภาพ",
        obStepStatusBody: "ตรวจสอบให้แน่ใจว่าทุกอย่างพร้อมสำหรับคุณสมบัติที่คุณต้องการ",
        obStatusRecheck: "ตรวจสอบอีกครั้ง",
        obStepDoneTitle: "พร้อมแล้ว!",
        obStepDoneBody: "Vorssaint ดูแล Mac ของคุณอยู่แล้ว",
        obDoneHint: "มองหาหลุมดำในแถบเมนูที่มุมขวาบนของหน้าจอ",
        obWhatsNewTitle: "มีอะไรใหม่ในเวอร์ชันนี้",
        obWhatsNewFallback: "การอัปเดตนี้รวมถึงการแก้ไขและการปรับปรุงล่าสุด",
        obLanguageUpdateTitle: "ตอนนี้เป็นภาษาของคุณ",
        obLanguageUpdateBody: "ปัจจุบัน Vorssaint พูดได้หลายภาษา เลือกอันที่คุณต้องการใช้ คุณสามารถเปลี่ยนได้ตลอดเวลาในการตั้งค่า",
        obPurposeTitle: "อะไรพาคุณมาที่นี่?",
        obPurposeBody: "เลือกการตั้งค่าที่พร้อมหรือเลือกสิ่งที่คุณต้องการใช้",
        obPurposeSkip: "คุณสามารถเพิ่มหรือลบคุณสมบัติในภายหลังได้ในการตั้งค่า",
        tabMonitor: "เฝ้าสังเกต",
        monitorMenuBarSection: "ในแถบเมนู",
        monitorMenuBarCaption: "เลือกสิ่งที่ปรากฏถัดจากไอคอนในแถบเมนู",
        monitorCombineTemperatures: "รวมการใช้งานและอุณหภูมิ",
        monitorCombineTemperaturesCaption: "เมื่อเปิดใช้งานการใช้งานและอุณหภูมิสำหรับรายการเดียวกัน ให้แสดงในบล็อกเดียว",
        monitorSeparateMenuBarMetrics: "แยกเมตริกออกเป็นรายการของตนเอง",
        monitorSeparateMenuBarMetricsCaption: "แยกบล็อกที่ใช้งานอยู่ในแถบเมนูและคงการใช้งานและอุณหภูมิไว้ด้วยกันเมื่อเปิดการรวม",
        monitorNetworkUploadFirst: "อัพโหลดด้านบนดาวน์โหลด",
        monitorShowCPU: "ซีพียู",
        monitorShowMemory: "หน่วยความจำ",
        monitorShowNetwork: "เครือข่าย",
        monitorShowPowerLabel: "พลัง",
        monitorIntervalLabel: "อัพเดททุกๆ.",
        monitorInterval1: "1 วินาที",
        monitorInterval2: "2 วินาที",
        monitorInterval5: "5 วินาที",
        monitorPanelSection: "ในแผง",
        panelNavigationMode: "นำทางแผงตามส่วน",
        panelNavigationCaption: "แสดงทีละส่วน เลือกรายการเพื่อดูทุกสิ่งในการเลื่อนอย่างต่อเนื่องเพียงครั้งเดียว",
        panelFooterSections: "ส่วนต่างๆ",
        panelFooterList: "รายการ",
        betaBadge: "เบต้า",
        betaFeatureWarning: "เบต้า คุณอาจพบข้อบกพร่องบางอย่าง",
        networkSection: "เครือข่าย",
        networkIPAddresses: "ที่อยู่ IP",
        networkLocalIP: "IPv4 ท้องถิ่น",
        networkDownload: "ดาวน์โหลด",
        networkUpload: "อัปโหลด",
        networkThisSession: "เซสชั่นนี้",
        networkMeasuring: "กำลังวัด...",
        networkApps: "แอพที่ใช้เครือข่าย",
        networkAppsIdle: "ไม่มีแอปที่ใช้เครือข่ายในขณะนี้",
        diskSection: "ดิสก์",
        diskUsed: "ใช้แล้ว",
        diskFree: "ฟรี",
        diskMenuBarStyleLabel: "รูปแบบแถบเมนูดิสก์",
        diskMenuBarUsedPercentage: "เปอร์เซ็นต์ที่ใช้",
        diskMenuBarAvailableSpace: "พื้นที่ว่าง",
        diskMenuBarUsedSpace: "พื้นที่ที่ใช้",
        diskAvailable: "มีอยู่",
        diskPurgeable: "ล้างได้",
        diskInternal: "ภายใน",
        diskExternal: "ภายนอก",
        diskSelect: "เลือกดิสก์",
        diskRead: "อ่าน",
        diskWrite: "เขียน",
        diskSMARTStatus: "สถานะ",
        diskSMARTUnavailable: "SMART ไม่พร้อมใช้งานสำหรับดิสก์นี้",
        diskTotalRead: "อ่านหมด",
        diskTotalWritten: "รวมเขียน",
        diskTemperature: "อุณหภูมิ",
        diskHealth: "สุขภาพ",
        diskPowerCycles: "วงจรไฟฟ้า",
        diskPowerOnHours: "เปิดเครื่องเป็นชั่วโมง",
        diskUnsafeShutdowns: "การปิดระบบที่ไม่ปลอดภัย",
        diskMediaErrors: "ข้อผิดพลาดของสื่อ",
        diskEject: "ดีดออก",
        diskEjectAll: "ดีดออกทั้งหมด",
        diskEjecting: "กำลังดีดออก...",
        diskReadyToRemove: "พร้อมถอด",
        diskEjectFailed: "ไม่สามารถดีดออกได้",
        diskProtectionCaption: "ดีดออกก่อนที่จะถอดปลั๊ก",
        diskNoExternal: "ไม่มีดิสก์ภายนอกที่พร้อมที่จะดีดออก",
        diskOpenInFinder: "เปิด",
        diskStorageSettings: "พื้นที่จัดเก็บข้อมูล",
        diskNoDisks: "ไม่พบดิสก์ที่ต่อเชื่อม",
        powerSection: "พลัง",
        powerSystem: "ระบบ",
        powerAdapter: "อะแดปเตอร์",
        powerBattery: "แบตเตอรี่",
        powerCharging: "กำลังชาร์จ",
        powerOnBattery: "เกี่ยวกับแบตเตอรี่",
        powerPluggedIn: "เสียบปลั๊กแล้ว",
        powerUnavailable: "ตัววัดพลังงานไม่พร้อมใช้งานบน Mac เครื่องนี้",
        powerAdapterMaxFormat: "อะแดปเตอร์แปลงไฟสูงสุด %@",
        monitorShowGPU: "จีพียู",
        monitorShowCPUTemperature: "อุณหภูมิซีพียู",
        monitorShowGPUTemperature: "อุณหภูมิของจีพียู",
        monitorShowBatteryTemperature: "อุณหภูมิแบตเตอรี่",
        monitorShowPeripheralBattery: "แบตเตอรี่อุปกรณ์ต่อพ่วง",
        peripheralBatteryNoDevices: "ไม่พบอุปกรณ์",
        monitorGraphsSection: "กราฟ",
        monitorGraphsCaption: "เลือกเมตริกที่ต้องการแสดงกราฟในช่วงเวลาต่างๆ",
        updateBannerTitle: "อัปเดตพร้อมใช้งาน",
        updateBannerAction: "อัปเดต",
        obStepMenuBarTitle: "หน่วยเมตริกในแถบเมนู",
        obStepMenuBarBody: "เลือกสิ่งที่จะแสดงถัดจากไอคอน ภาพตัวอย่างด้านบนอัปเดตแบบสด",
        obStepMenuBarNote: "ใหม่: บล็อกเครือข่ายและพลังงานและกราฟในแผงควบคุม ปรับแต่งทั้งหมดในภายหลังในการตั้งค่า > จอภาพ",
        monitorMenuBarPresetLabel: "สไตล์",
        menuBarPresetReadable: "อ่านได้",
        menuBarPresetDense: "หนาแน่น",
        menuBarSpacingLabel: "ระยะห่างของแถบเมนู",
        menuBarSpacingStandard: "มาตรฐาน",
        menuBarSpacingCompact: "กะทัดรัด",
        menuBarHideIconToggle: "ซ่อนไอคอนแอปขณะแสดงเมตริก",
        menuBarHideIconCaption: "ไอคอนจะกลับมาเองเมื่อหน่วยวัดออกจากแถบและเมื่อมีบางอย่างให้ส่งสัญญาณ (พร้อมอัปเดตหรือปิดเสียงไมโครโฟน)",
        monitorLabelStyleLabel: "ป้ายกำกับ",
        menuBarLabelStyleCompact: "กะทัดรัด",
        menuBarLabelStyleClassic: "คลาสสิค",
        monitorMemoryStyleLabel: "แสดงหน่วยความจำเป็น",
        monitorMemoryPressureDot: "จุดดัน",
        memoryStyleDot: "จุด",
        memoryStylePercent: "%",
        memoryStyleBoth: "ทั้งคู่",
        systemUptime: "ขึ้นเพื่อ",
        batteryCharge: "ค่าใช้จ่าย",
        powerHealth: "สุขภาพแบตเตอรี่",
        powerCycles: "รอบ",
        speedTestRun: "ทดสอบความเร็ว",
        speedTestAgain: "ทดสอบอีกครั้ง",
        speedTestLatency: "เวลาแฝง",
        speedTestTesting: "กำลังทดสอบ...",
        speedTestFailed: "การทดสอบล้มเหลว",
        monitorShowInPanel: "แสดงในแผง",
        disclosureExpanded: "ขยายแล้ว",
        disclosureCollapsed: "ยุบแล้ว",
        panelHideItem: "ซ่อนจากแผง",
        panelShowItem: "แสดงในแผง",
        panelHiddenItem: "ที่ซ่อนอยู่",
        monitorItemUptime: "เวลาทำงาน",
        monitorItemNetSpeed: "ความเร็วสด",
        monitorItemNetTotals: "ผลรวมเซสชัน",
        monitorItemNetTest: "ทดสอบความเร็ว",
        monitorItemDiskUsage: "การใช้งานดิสก์",
        monitorItemDiskActivity: "กิจกรรมสด",
        monitorItemDiskSMART: "ปราดเปรื่อง",
        monitorItemDiskProtection: "การป้องกันภายนอก",
        monitorItemDiskTools: "เครื่องมือ",
        monitorPanelConfigHint: "เปิดบล็อกเพื่อเลือกสิ่งที่จะแสดง",
        monitorOrderHint: "ลากเพื่อจัดลำดับส่วนของแผงใหม่ และใช้ดวงตาเพื่อแสดงหรือซ่อนแต่ละส่วน",
        obStepPanelTitle: "มีอะไรอยู่ในแผงควบคุม",
        obStepPanelBody: "เปิดแต่ละบล็อกและเลือกสิ่งที่จะแสดงเมื่อคุณคลิกที่ไอคอน",
        obStepPanelNavigationTitle: "แผงตามส่วน",
        obStepPanelNavigationBody: "ขณะนี้แผงสามารถแสดงได้ครั้งละหนึ่งส่วน คุณสามารถสลับระหว่างส่วนและรายการในการตั้งค่า",
        cleaningMenuItem: "โหมดการทำความสะอาด",
        utilitiesSection: "สาธารณูปโภค",
        quickControlsSection: "การควบคุม",
        panelCategoryWindows: "หน้าต่าง",
        panelCategoryInput: "เมาส์และคีย์บอร์ด",
        panelCategoryFiles: "ไฟล์",
        windowMaximizeName: "ขยายหน้าต่างให้ใหญ่สุด",
        windowMaximizeCaption: "ปุ่มสีเขียวจะขยายใหญ่สุดโดยไม่ต้องสร้าง Space อื่น",
        windowMaximizeActiveNow: "ปุ่มสีเขียวแทนที่ทำงานอยู่",
        windowMaximizeNeedsAccessibility: "ต้องการความสามารถในการเข้าถึงในการทำงาน",
        keyDebounceName: "เดเด้ง",
        keyDebounceEnable: "กรองคีย์ที่ซ้ำกัน",
        keyDebounceCaption: "กรองการกดปุ่มซ้ำอย่างรวดเร็ว",
        keyDebounceActiveNow: "ตัวกรองทำงานอยู่",
        keyDebounceGlobalWindow: "หน้าต่างสากล",
        keyDebouncePerKeySection: "คีย์เฉพาะ",
        keyDebouncePerKeyCaption: "ค่าต่อคีย์จะแทนที่หน้าต่างส่วนกลาง ใช้ 0 ms เพื่อหยุดการกรองคีย์",
        keyDebounceKeyLabel: "สำคัญ",
        keyDebounceWindowLabel: "หน้าต่าง",
        keyDebounceAddKey: "เพิ่มรหัส",
        keyDebounceNoOverrides: "ไม่มีการกำหนดค่าคีย์เฉพาะ",
        keyDebounceRemoveKey: "เอากุญแจออก",
        cleaningPanelCaption: "ล็อคคีย์บอร์ดเพื่อให้คุณทำความสะอาดได้อย่างปลอดภัย",
        cleaningOverlayTitle: "คีย์บอร์ดถูกล็อคเพื่อทำความสะอาด",
        cleaningOverlaySubtitle: "กด Escape 5 ครั้งเพื่อปลดล็อค",
        cleaningOverlayUnlock: "ปลดล็อค",
        cleaningOverlayMouseHint: "เมาส์และแทร็กแพดของคุณยังคงใช้งานได้",
        cleaningKeepScreenVisibleToggle: "ให้มองเห็นหน้าจอได้",
        cleaningKeepScreenVisibleCaption: "แสดงตัวบ่งชี้ที่รอบคอบที่มุมของหน้าจอ แทนที่จะทำให้เนื้อหามืดลง",
        cleaningStartNow: "ล็อคแป้นพิมพ์ทันที",
        cleaningNeedsAxTitle: "จำเป็นต้องมีการเข้าถึง",
        cleaningNeedsAxBody: "เพื่อล็อคคีย์บอร์ดอย่างปลอดภัย Vorssaint จำเป็นต้องได้รับอนุญาตจากการเข้าถึง ให้สิทธิ์ในการตั้งค่าระบบแล้วลองอีกครั้ง",
        tabSupport: "สนับสนุน",
        shortcutsPageCaption: "แก้ไขทางลัดส่วนกลางทั้งหมดจากคุณสมบัติที่ติดตั้งบน Mac เครื่องนี้ ทางลัดที่ไม่ได้ใช้งานจะยังคงบันทึกไว้แต่จะไม่ทำงาน",
        shortcutsPageTitle: "แป้นพิมพ์ลัด",
        settingsSearchPlaceholder: "การตั้งค่าการค้นหา",
        donateHeading: "ช่วยให้ Vorssaint เติบโตต่อไป",
        donateMessage: "Vorssaint เป็นอิสระ เป็นอิสระ และสร้างขึ้นในเวลาว่างของฉัน หากคุณต้องการบริจาคทางการเงิน Buy Me a Coffee ช่วยให้ฉันพัฒนาการพัฒนาไปข้างหน้าได้โดยตรง",
        donateButton: "เลี้ยงกาแฟผ่าน Buy Me a Coffee",
        donateThanks: "ขอบคุณที่อยู่ที่นี่ 🖤",
        supportIntroTitle: "ช่วยให้ Vorssaint เติบโตต่อไป",
        supportIntroMessage: "หากคุณต้องการสนับสนุนการพัฒนาทางการเงิน Buy Me a Coffee คือที่เดียวที่ทำได้",
        supportIntroStarButton: "Star Vorssaint บน GitHub",
        supportIntroStarMessage: "ให้ดาวบน GitHub เพื่อสนับสนุนโครงการ",
        supportIntroCoffeeButton: "Buy Me a Coffee",
        supportIntroLaterButton: "ไม่ใช่ตอนนี้",
        supportIntroDoneButton: "เสร็จสิ้น",
        discordIntroTitle: "ชุมชน Vorssaint Discord เพิ่งเริ่มต้นเท่านั้น",
        discordIntroMessage: "ชุมชน Vorssaint กำลังสร้างขึ้นเพื่อพูดคุย แนะนำฟีเจอร์ และแจ้งปัญหา เข้าร่วมกับเราได้บน Discord",
        discordIntroJoinButton: "เข้าร่วม Discord",
        communityIntroTitle: "เห็นมันก่อนใครๆ",
        communityIntroMessage: "ติดตามข่าวสารและพรีวิวฟีเจอร์ใหม่บน X",
        communityIntroFollowButton: "ติดตาม @vorssaint บน X",
        homebrewOfficialIntroTitle: "ขณะนี้อยู่ในแค็ตตาล็อก Homebrew อย่างเป็นทางการ",
        homebrewOfficialIntroMessage: "Vorssaint สามารถติดตั้งได้โดยตรงจากแค็ตตาล็อก Homebrew อย่างเป็นทางการ",
        homebrewOfficialIntroInstallLabel: "ติดตั้งใหม่",
        homebrewOfficialIntroMigrationTitle: "ใช้ก๊อกน้ำแบบเก่าเหรอ?",
        homebrewOfficialIntroMigrationMessage: "ถอดก๊อกออกหนึ่งครั้ง แอปและการตั้งค่าของคุณยังคงอยู่",
        homebrewOfficialIntroCopyButton: "คำสั่งคัดลอก",
        updateShowcaseTitle: "มีอะไรใหม่ใน 3.1.4",
        updateShowcaseMessage: "ดูการปรับปรุงหลักๆ ในการอัปเดตนี้อย่างรวดเร็ว",
        updateShowcaseUnavailable: "ไม่สามารถโหลดวิดีโอได้ในขณะนี้ คุณยังสามารถดำเนินการต่อได้",
        updateShowcaseRestart: "รีสตาร์ท",
        showMenuBarIcon: "แสดงไอคอนแถบเมนู",
        menuBarIconStillHiddenTitle: "ไอคอนยังคงซ่อนอยู่",
        menuBarIconStillHiddenBody: "ไอคอนถูกสร้างขึ้นใหม่ แต่ macOS ไม่ได้ทำให้มีจุดที่มองเห็นได้ แถบเมนูอาจไม่มีพื้นที่ว่าง: ลบไอคอนแถบเมนูบางส่วน (หรือปิดแอปที่มีเมนูยาว) แล้วลองอีกครั้ง",
        menuBarIconManagerHintFormat: "%@ เปิดอยู่และอาจเก็บไอคอนไว้ในส่วนที่ซ่อนอยู่ มองหา Vorssaint ที่นั่น หรือตั้งค่า %@ ให้แสดง Vorssaint เสมอ",
        menuBarIconDisallowedBody: "macOS กำลังกัน Vorssaint ออกจากแถบเมนู เปิดการตั้งค่าระบบ > แถบเมนู ค้นหา Vorssaint ในรายการแอป และเปิด \"อนุญาตในแถบเมนู\" ไอคอนจะปรากฏขึ้นทันทีที่สวิตช์เปิดอยู่",
        shortcutRecording: "กดปุ่มเพื่อบันทึก",
        shortcutReset: "รีเซ็ต",
        shortcutNone: "ไม่มี",
        shortcutClear: "ลบทางลัด",
        shortcutInvalid: "ใช้ปุ่มควบคุม ตัวเลือก หรือคำสั่งเป็นอย่างน้อย",
        shortcutPressKeys: "กดปุ่มลัด",
        shortcutEscapeHint: "กด Esc เพื่อยกเลิก",
        shortcutDeleteHint: "กด Delete เพื่อล้าง",
        shortcutNotCaptured: "ไม่มีอะไรถูกจับ macOS หรือแอพอื่นใช้ชุดค่าผสมนั้นอยู่แล้ว ลองอันอื่น",
        shortcutConflictFormat: "ทางลัดนี้ถูกใช้โดย %@ แล้ว",
        shortcutTakeOverOffer: "macOS ใช้ %@ สำหรับทางลัดอันใดอันหนึ่งของตัวเอง",
        shortcutTakeOverAction: "เข้าควบคุมขณะที่ Vorssaint วิ่ง",
        shortcutTakeOverCaption: "macOS จะได้รับกุญแจคืนทุกครั้งที่ Vorssaint ไม่ทำงานหรือคุณสมบัตินี้ปิดอยู่",
        shortcutTakeOverDismiss: "อย่ารับช่วงต่อ",
        shortcutUnavailable: "macOS ปฏิเสธทางลัดนี้ เลือกอันอื่น",
        shelfShortcutToggle: "ทางลัดชั้นวาง",
        switcherUsageHintFormat: "กด %@ ค้างไว้เพื่อนำทาง; ปล่อยเพื่อเปิดใช้งานหน้าต่าง Shift หรือ ← ย้อนกลับ; W ปิดหน้าต่าง Q ออกจากแอป Esc ยกเลิก",
        musicBlockSection: "ปุ่มมีเดีย",
        musicBlockTitle: "หยุดไม่ให้ Music เปิดขึ้นมาเอง",
        musicBlockCaption: "บล็อกการเปิดแอปเพลงหลังจากตรวจพบคีย์สื่อ ต้องมีการเข้าถึงการเข้าถึง คำสั่งของหูฟังที่ไม่มีคีย์ที่ตรวจพบจะถูกทิ้งไว้ตามลำพัง",
        musicBlockUnavailable: "การป้องกันนี้ไม่พร้อมใช้งานในขณะนี้ ปิดและเปิดใหม่เพื่อลองอีกครั้ง",
        musicBlockReplacementLabel: "เปิดแทน.",
        musicBlockReplacementNone: "ไม่มี",
        musicBlockReplacementBlocked: "เพลงและ iTunes เป็นแอพที่ถูกบล็อก ดังนั้นจึงไม่สามารถเปิดแทนได้ เลือกแอปอื่น",
        musicBlockChooseApp: "เลือกแอป...",
        musicBlockPlayReplacement: "เล่นหลังจากเปิดการเปลี่ยน",
        cleanerName: "ทำความสะอาด",
        cleanerIntroTitle: "ทำความสะอาด Mac ของคุณ",
        cleanerIntroCaption: "สแกนหาสิ่งที่เหลือจากแอปที่ถอนการติดตั้ง แคช บันทึก และถังขยะ คุณตรวจสอบทุกอย่างก่อน และรายการที่ถูกลบจะถูกส่งไปยังถังขยะ",
        cleanerScan: "สแกน",
        cleanerScanning: "กำลังสแกน...",
        cleanerCleaning: "กำลังทำความสะอาด...",
        cleanerCatLeftovers: "ที่เหลือจากแอพที่ถอนการติดตั้ง",
        cleanerCatLoginItems: "รายการเริ่มต้นกำพร้า",
        cleanerCatCaches: "แคช",
        cleanerCatLogs: "บันทึก",
        cleanerCatDeveloper: "ขยะของนักพัฒนา",
        cleanerCatTrash: "ขยะ",
        cleanerLeftoversNote: "พบโดยการวิเคราะห์และไม่ทำเครื่องหมาย ตรวจสอบเส้นทางก่อนติ๊ก",
        cleanerLoginItemsNote: "รายการภายใต้รายการเข้าสู่ระบบจะหายไปหลังจากรีสตาร์ท Mac",
        cleanerTrashNote: "การล้างถังขยะจะมีผลถาวร",
        cleanerCatDeviceBackups: "ข้อมูลสำรองไอโฟน",
        cleanerDeviceBackupsCaption: "ข้อมูลสำรองของ iPhone และ iPad เก่ากินพื้นที่จัดเก็บข้อมูลขนาดใหญ่ที่ macOS เรียกว่า \"อื่นๆ\" ลบเฉพาะสิ่งที่คุณไม่ต้องการอีกต่อไป การสำรองข้อมูลใหม่จะเกิดขึ้นเมื่อคุณเสียบอุปกรณ์อีกครั้ง",
        cleanerCatScreenshots: "ภาพหน้าจอที่ถูกลืม",
        cleanerScreenshotsCaptionFormat: "ภาพหน้าจอที่คุณไม่ได้เปิดใน %d วันที่ยังมีชื่อและโฟลเดอร์ที่ macOS มอบให้ คนที่คุณเปลี่ยนชื่อหรือย้ายจะไม่ปรากฏที่นี่",
        cleanerScreenshotsSettingCaption: "การสแกนจะแสดงรายการภาพหน้าจอที่คุณไม่ได้เปิดมานานขนาดนี้ โดยไม่ได้เลือก พร้อมขนาดโดยรวม",
        cleanerScreenshotsAfterFormat: "หลังจาก %d วัน",
        cleanerNothingFound: "ไม่มีอะไรจะทำความสะอาด Mac ของคุณเป็นระเบียบเรียบร้อย",
        cleanerClean: "ทำความสะอาด",
        cleanerDoneNote: "รายการต่างๆ ไปที่ถังขยะและสามารถกู้คืนได้จากที่นั่น",
        cleanerAgain: "สแกนอีกครั้ง",
        cleanerRevealInFinder: "เปิดเผยใน Finder",
        cleanerPanelCaption: "แอพที่เหลือ แคช และบันทึก",
        cleanerSafeSection: "การล้างข้อมูลที่ปลอดภัย",
        cleanerOptionalSection: "ไม่บังคับ ให้ตรวจสอบก่อน",
        cleanerCatOtherCaches: "แคชอื่น ๆ",
        cleanerCachesCaption: "แอพไฟล์ชั่วคราวสร้างขึ้นใหม่ด้วยตัวเอง",
        cleanerLogsCaption: "บันทึกการวินิจฉัยเก่า",
        cleanerDeveloperCaption: "สิ่งที่เหลืออยู่ของการสร้างและจำลอง Xcode",
        cleanerLoginItemsCaption: "รายการเริ่มต้นที่เหลือจากแอปที่ไม่มีอยู่อีกต่อไป",
        cleanerLeftoversCaption: "ไฟล์ที่แอปที่คุณถอนการติดตั้งทิ้งไว้",
        cleanerOtherCachesCaption: "ปลอดภัยในการถอดออก ไม่มีอะไรแตกหัก แอพอาจเปิดช้าลงหนึ่งครั้งและดาวน์โหลดเนื้อหา เช่น เพลงออฟไลน์ ดาวน์โหลดอีกครั้ง",
        cleanerCleanSizeFormat: "ทำความสะอาด %@",
        cleanerScheduleTitle: "การล้างข้อมูลอัตโนมัติ",
        cleanerScheduleOff: "ปิด",
        cleanerScheduleDaily: "ทุกวัน",
        cleanerScheduleWeekly: "ทุกสัปดาห์",
        cleanerScheduleCaption: "ทำความสะอาดเฉพาะส่วนที่ปลอดภัยด้วยตัวเองตามเวลาที่เลือก และส่งทุกอย่างไปที่ถังขยะ",
        cleanerScheduleLastFormat: "การล้างข้อมูลอัตโนมัติครั้งล่าสุดทำให้ %@ เป็นอิสระ",
        cleanerAutoNotificationFormat: "%@ ปลดปล่อยและส่งไปที่ถังขยะ",
        cleanerScheduleNextFormat: "การล้างข้อมูลครั้งต่อไป %@",
        cleanerScheduleRanFormat: "การล้างข้อมูลอัตโนมัติครั้งล่าสุด %@",
        cleanerScheduleNotifyToggle: "แจ้งให้ทราบเมื่อเสร็จสิ้น",
        cleanerNotifDenied: "การแจ้งเตือน Vorssaint ถูกปิดในระบบ",
        cleanerNotifOpenSettings: "เปิดการตั้งค่าการแจ้งเตือน...",
        launchAtLoginNeedsApplications: "แอปกำลังทำงานจากตำแหน่งที่ไม่สามารถเปิดเมื่อเข้าสู่ระบบได้ ลาก Vorssaint ไปที่โฟลเดอร์ Applications เปิดจากที่นั่นแล้วเปิดอีกครั้ง",
        launchAtLoginNeedsApproval: "รายการเข้าสู่ระบบได้รับการลงทะเบียนแล้ว แต่ยังคงปิดอยู่ในการตั้งค่าระบบ เปิดการตั้งค่าระบบ > ทั่วไป > รายการเข้าสู่ระบบและส่วนขยาย และเปิด Vorssaint ภายใต้เปิดเมื่อเข้าสู่ระบบ",
        ocrRemoveLineBreaksToggle: "ลบตัวแบ่งบรรทัด",
        ocrRemoveLineBreaksCaption: "ลบตัวแบ่งบรรทัดเพื่อวางข้อความที่คัดลอกไว้เป็นหนึ่งย่อหน้า",
        ocrQRToggle: "อ่านรหัส QR",
        ocrQRCaption: "หากพื้นที่นั้นมีรหัส QR เนื้อหาจะแสดงขึ้นเพื่อคัดลอกหรือเปิด",
        ocrQRCopied: "คัดลอกรหัส QR แล้ว",
        qrResultTitle: "รหัส QR",
        qrResultCopy: "คัดลอก",
        qrResultOpen: "เปิดลิงก์",
        highlightsTitle: "สิ่งใหม่ในการอัปเดตนี้",
        highlightsTitleClipboardRedesign: "คลิปบอร์ดที่ออกแบบใหม่",
        highlightsTitleWindowLayout: "เค้าโครงหน้าต่าง",
        highlightsTitleQuitProtection: "ออกและปิดการป้องกัน",
        highlightsTitleRecorderBlur: "กำลังบันทึกภาพเบลอความเป็นส่วนตัว",
        highlightsCaptionDockPreview: "การแสดงตัวอย่าง Dock ใช้งานได้เมื่อเปิดการขยาย Dock ไว้",
        highlightsCaptionScreenshot: "เครื่องมือจับภาพหน้าจอได้รับ Loupe พิกเซลและการอ่านโค้ด QR",
        highlightsCaptionSnippetLibrary: "เมนูตัวอย่างที่ค้นหาได้จะพิมพ์ตัวอย่างข้อมูลไว้ที่เคอร์เซอร์ของคุณ",
        highlightsCaptionCapturePalette: "ตอนนี้ทางลัดหนึ่งรายการจะเปิดจานสีแบบลอยสำหรับภาพหน้าจอ การบันทึก ข้อความบนหน้าจอ และสีด้วยตัวควบคุมที่อยู่ใกล้เคียง",
        highlightsCaptionClipboardRedesign: "ขณะนี้ประวัติคลิปบอร์ดเปิดเป็นพาเล็ตขนาดกะทัดรัดพร้อมแถวที่ไม่เกะกะ และการดูตัวอย่างตามความต้องการสำหรับการอ่านหรือแก้ไขรายการทั้งหมด",
        highlightsCaptionWindowLayout: "วางตำแหน่งหน้าต่างด้วยวงแหวนทิศทางโดยใช้ทางลัดและตัวชี้ หรือลากไปที่ขอบหน้าจอเพื่อจัดชิดด้วยช่องว่างแบบกำหนดเอง",
        highlightsCaptionQuitProtection: "หลีกเลี่ยงการออกจากแอปหรือปิดหน้าต่างโดยไม่ได้ตั้งใจด้วยการพัก การกดสองครั้ง หรือตัวปรับแต่งเพิ่มเติม ซึ่งปรับแต่งได้สำหรับแต่ละแอป",
        highlightsCaptionRecorderBlur: "ซ่อนรายละเอียดส่วนตัว รหัสผ่าน และพื้นที่ละเอียดอ่อนทุกที่ในวิดีโอที่บันทึกไว้ก่อนที่จะแชร์หรือส่งออก",
        highlightsConfigure: "ตั้งค่า",
        highlightsTry: "ลองมัน",
        highlightsSeeAll: "ดูการเปลี่ยนแปลงทั้งหมด",
        switcherCurrentSpaceOnly: "แสดงเฉพาะเดสก์ท็อปปัจจุบัน",
        switcherCurrentSpaceOnlyCaption: "แสดงเฉพาะหน้าต่างบนเดสก์ท็อปปัจจุบัน",
        shelfFileMissing: "ไฟล์ไม่มีอยู่อีกต่อไป",
        previewSizeSmall: "เล็ก",
        mixerSoundEffectsOutputTitle: "เสียงเอฟเฟกต์ระบบ",
        mixerSoundEffectsOutputTooltip: "ส่งเสียงแจ้งเตือนและเอฟเฟกต์ไปยังอุปกรณ์นี้",
        monitorOpenActivityMonitor: "เปิดตัวตรวจสอบกิจกรรม",
        dockClickHide: "คลิกไอคอน Dock เพื่อซ่อนแอป",
        dockClickHideCaption: "แอพที่ใช้งานอยู่จะซ่อนเมื่อคุณคลิกไอคอน Dock คลิกอีกครั้งเพื่อนำกลับมา",
        monitorMemoryMetricLabel: "วัดหน่วยความจำเป็น",
        memoryMetricUsed: "หน่วยความจำที่ใช้",
        memoryMetricApp: "หน่วยความจำแอป",
        keepAwakeRightClickToggle: "คลิกขวาเพื่อสลับเปิด/ปิด",
        keepAwakeRightClickToggleCaption: "คลิกขวาที่ไอคอนแถบเมนูเพื่อเปิดหรือปิดการคงสถานะตื่นทันที",
        urlCleanerRulesTitle: "กฎการทำความสะอาด",
        urlCleanerRulesCaption: "ไซต์แนบพารามิเตอร์เหล่านี้เข้ากับลิงก์แชร์ของตนเองเพื่อติดตามว่าลิงก์มาจากไหน เมื่อเปิดสวิตช์ ชื่อจะถูกลบออกเมื่อมีการล้างลิงก์ ปิดเครื่อง มันก็ยังคงอยู่ ชื่อที่คุณเพิ่มสามารถลบได้",
        urlCleanerRulesCoverageCaption: "รายการนี้ครอบคลุมเส้นทางการแชร์ที่แตกต่างกันของเว็บไซต์ (หน้าเว็บ แอป ห้องถ่ายทอดสด) ซึ่งเป็นเหตุผลว่าทำไมมันถึงยาว ลิงก์จริงมักจะมีเพียงสองถึงสี่ลิงก์เท่านั้น",
        urlCleanerRulesAllSites: "เว็บไซต์ทั้งหมด",
        urlCleanerRulesCountSingular: "1 พารามิเตอร์",
        urlCleanerRulesCountPluralFormat: "พารามิเตอร์ %d",
        urlCleanerRulesAddSite: "เพิ่มเว็บไซต์",
        urlCleanerRulesParameterPlaceholder: "ชื่อพารามิเตอร์",
        urlCleanerRulesMatchCaption: "เขียนชื่อทางด้านซ้ายของ = เช่น utm_source ชื่อที่ตรงกันจะนำพารามิเตอร์ตัวหนึ่งออกจากลิงก์ และปล่อยให้ส่วนที่เหลือเหมือนเดิม",
        urlCleanerRulesAddButton: "เพิ่ม",
        urlCleanerRulesRemoveButton: "ลบชื่อ",
        urlCleanerRulesRemoveSiteButton: "ปิดทุกกฎสำหรับไซต์นี้",
        urlCleanerRemovedFormat: "ลบ %@ แล้ว",
        switcherSearchPin: "ปักหมุดค้นหาด้วย S",
        switcherSearchPinCaption: "S เริ่มการค้นหาและปักหมุดตัวสลับที่เปิดอยู่ ดังนั้นการพิมพ์จึงไม่สร้างอักขระพิเศษอีกต่อไปเมื่อคำสั่งลัดของคุณใช้ ⌥ และการค้นหาที่ขึ้นต้นด้วย Q หรือ W จะไม่ปิดหน้าต่างหรือออกจากแอพโดยไม่ได้ตั้งใจอีกต่อไป",
        invertVerticalScroll: "สลับการเลื่อนแนวตั้ง",
        invertHorizontalScroll: "สลับการเลื่อนแนวนอน",
        scrollHorizontalName: "เลื่อนไปด้านข้างขณะกดคีย์ค้างไว้",
        scrollHorizontalModifierLabel: "คีย์ตัวปรับแต่ง",
        scrollHorizontalCommandKey: "สั่งการ",
        scrollHorizontalCaption: "กดเฉพาะตัวปรับแต่งที่เลือกไว้เพื่อเลื่อนล้อเมาส์แนวตั้งในแนวนอน การกดคีย์ผสมอื่นๆ จะไม่เปลี่ยนแปลง",
        switcherShowShortcutHints: "แสดงคำแนะนำทางลัด",
        switcherShowShortcutHintsCaption: "แสดงทางลัดของแอปและหน้าต่างด้านล่างไอคอน",
        uninstallerHomebrewPackageFormat: "%@ จะถูกลบออกจาก Homebrew ด้วย",
        shelfEdgeToggle: "เปิดใกล้ขอบหน้าจอ",
        shelfEdgeCaption: "ลากไฟล์ไปทางขอบหน้าจอเพื่อดูชั้นวางเข้าไป วางลงตรงนั้น หรือดึงกลับแล้วถอยกลับ",
        focusFollowsMouseName: "โฟกัสตามเมาส์",
        focusFollowsMouseCaption: "ปรับโฟกัสและยกหน้าต่างใต้ตัวชี้ขึ้นหลังจากหยุดชั่วครู่",
        focusFollowsMouseDelay: "โฮเวอร์ล่าช้า",
        switcherMinimizedPlacementLabel: "หน้าต่างย่อเล็กสุด",
        switcherTreatHiddenAppsLikeMinimized: "ปฏิบัติต่อแอปที่ซ่อนอยู่เช่นหน้าต่างย่อเล็กสุด",
        switcherMinimizedPlacementNormal: "สั่งได้ปกติ",
        switcherMinimizedPlacementEnd: "วางที่ส่วนท้าย",
        switcherMinimizedPlacementHidden: "ซ่อน",
        switcherShowFullscreenWindows: "แสดงหน้าต่างแบบเต็มหน้าจอ",
        switcherScreenPlacementLabel: "แสดงต่อ",
        switcherScreenPlacementPointer: "หน้าจอด้วยตัวชี้",
        switcherScreenPlacementMenuBar: "หน้าจอด้วยแถบเมนู",
        switcherScreenPlacementActiveWindow: "หน้าจอพร้อมหน้าต่างที่ใช้งานอยู่",
        switcherScreenPlacementCaption: "ซึ่งจอแสดงผลตัวสลับจะเปิดขึ้นเมื่อมีการเชื่อมต่อมากกว่าหนึ่งรายการ",
        switcherCurrentDisplayOnly: "แสดงเฉพาะการแสดงผลปัจจุบัน",
        switcherCurrentDisplayOnlyCaption: "แสดงรายการเฉพาะหน้าต่างบนจอแสดงผลใต้ตัวชี้ หากจอแสดงผลนั้นไม่มีหน้าต่าง ตัวสลับจะไม่เปิดขึ้น",
        smoothScrollResponseLabel: "การตอบสนอง",
        smoothScrollCoastLabel: "การเคลื่อนที่ต่อเนื่อง",
        mouseAccelerationName: "ปิดการใช้งานการเร่งความเร็วของเมาส์",
        mouseAccelerationCaption: "ลบการเร่งความเร็วของตัวชี้สำหรับเมาส์ที่เชื่อมต่อ การตั้งค่าก่อนหน้าของคุณจะกลับมาเมื่อปิดการตั้งค่านี้หรือ Vorssaint ปิด",
        shelfClearOnClose: "ล้างรายการเมื่อปิด",
        shelfClearOnCloseCaption: "ลบไฟล์ทั้งหมดบน Shelf เมื่อปิดแผง"
    )
}
